### ISSUE TITLE
Breaking change violating SemVer rules

### ISSUE THREAD

**Issue by kellcomnet2** [Humanizr/Humanizer#1013]
Please see https://github.com/icsharpcode/ILSpy/issues/2232

The decompiler expects: System.String Humanizer.InflectorExtensions.Singularize(System.String, Boolean)
The newer Humanizer only offers: System.String Humanizer.InflectorExtensions.Singularize(System.String, Boolean, Boolean).

The breaking change is due to the added optional parameter. Note that both are from the same major version, seems like Humanizer does not follow semver rules... not sure how we could fix this.

**Comment by clairernovotny** [comment]
This certainly wasn't intentional. Can you please submit a PR with an overload containing the original parameters and we'll get an update out.

**Comment by SimonCropp** [comment]
Closing due to no response
