### ISSUE TITLE
Pluralizer bug

### ISSUE THREAD

**Issue by ErikEJ** [Humanizr/Humanizer#1030]
Bug:
Pluralize or Singularize `Training`
Expected: `Training`
Actual: `training` (lower case t)

See https://github.com/dotnet/efcore/issues/24040

**Comment by ErikEJ** [comment]
Looks like all 7 words here ignore casing of original word: https://github.com/Humanizr/Humanizer/blame/master/src/Humanizer/Inflections/Vocabularies.cs#L97

**Comment by GatorEcho** [comment]
I'm new to open source but I would like to fix this.

**Comment by cgountanis** [comment]
Not fixed yet? Seems like an easy one to fix. Not sure why using extra stuff is becoming default. Remember this new EF is going to be simple and basic, otherwise people will run away. Hard enough getting new devs to use it after the old EF experience. I get the reason for plurals but does it have to be so evasive?

**Comment by ErikEJ** [comment]
@clairernovotny Great, when is a new release planned with the fix?

**Comment by clairernovotny** [comment]
Soon as I can narrow down the cause of the test failures here:
https://github.com/Humanizr/Humanizer/pull/1055

https://dev.azure.com/dotnet/Humanizer/_build/results?buildId=50646&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=4cf9c106-f8f4-5b50-808b-a1dd5e6dbc8a

**Comment by ErikEJ** [comment]
That's.... Interesting!

**Comment by ErikEJ** [comment]
@cgountanis This fix is now included in the latest build of EF Core Power Tools

**Comment by clairernovotny** [comment]
@ErikEJ make sure you're using 2.9.9 as I had to remove fil-PH by default as it was causing NuGet restore issues. #1057

**Comment by ErikEJ** [comment]
@clairernovotny Thanks, I noticed!

**Comment by cgountanis** [comment]
Thanks Erik, looks like they fixed it at some point in the next Sprint or release as well. Not trying to ignore the power tools but I really don't want to use any third-party stuff for obvious reasons.
