### ISSUE TITLE
Inflection singularizes Databases to Databasis

### ISSUE THREAD

**Issue by Nefcanto** [Humanizr/Humanizer#1042]
Hello.

Thank you for this great library.

Simply run this code:

var singular = "Databases".Singularize();

The result would be "Databasis".

I just thought to report it back so you may fix it. I solved my problem in a different way.

Thank you.

**Comment by hangy** [comment]
It really shouldn't as it's already added as an exception: https://github.com/Humanizr/Humanizer/blob/896ded1c66c48f9d77ab2cb985cfa41e427f874e/src/Humanizer.Tests.Shared/InflectorTests.cs#L304 Do you remember which version of Humanizer you tested this in?
