### ISSUE TITLE
Parse `ByteSize` with `IFormatProvider`?

### ISSUE THREAD

**Issue by dahlbyk** [Humanizr/Humanizer#1061]
While poking around for #1060 I noticed `CultureInfo.CurrentCulture` in [`ByteSize.TryParse()`](https://github.com/Humanizr/Humanizer/blob/1285835f92626619ed2d678c8910b1a8a21fcf6e/src/Humanizer/Bytes/ByteSize.cs#L455): https://github.com/Humanizr/Humanizer/blob/1285835f92626619ed2d678c8910b1a8a21fcf6e/src/Humanizer/Bytes/ByteSize.cs#L474

Would you be interested `TryParse`/`Parse` overloads that accept `IFormatProvider`? Asking first since it's a public API change.

It would check if the `IFormatProvider` is either `CultureInfo` or a `NumberFormatInfo`.

**Comment by clairernovotny** [comment]
Can we do it with a new overload? I'm okay with adding overloads; been trying to avoid breaking changes for the most part.

**Comment by dahlbyk** [comment]
Yeah, should have clarified I meant an additive public API change.

While we're here, there's also a reference to `CurrentCulture` here: https://github.com/Humanizr/Humanizer/blob/12cc40033da9a18a19d0da419a1d39ab9ae76dba/src/Humanizer/Transformer/ToLowerCase.cs#L7-L10

But not here:
https://github.com/Humanizr/Humanizer/blob/12cc40033da9a18a19d0da419a1d39ab9ae76dba/src/Humanizer/Transformer/ToUpperCase.cs#L5-L8

Seems like they should be consistent? Is there any value in allowing a culture-specific transform?

**Comment by clairernovotny** [comment]
TBH, it's been so long since I've looked at that code. It does seem odd and I agree that CurrentCulture should be used where appropriate. 

I'm not sure if having a culture aware one makes a difference, but I'm open to additional overloads that take the culture.

**Comment by dahlbyk** [comment]
> TBH, it's been so long since I've looked at that code. It does seem odd and I agree that CurrentCulture should be used where appropriate.

`ToUpper()` uses `CurrentCulture`, so the behavior is close to the same. The only difference is a `NullReferenceException` vs `ArgumentNullException` given `null`.

At minimum we can fix the NullRef here and in `ToSentenceCase`. I would argue that since `null` handling isn't well-defined, it's just as useful for most transforms to short-circuit and return `null` instead of throwing.

> I'm not sure if having a culture aware one makes a difference, but I'm open to additional overloads that take the culture.

Can't overload the `To` properties that return the given transformers, but I think it could work to do something like this:

```csharp
// Better name ideas?
public interface ICulturedStringTransformer : IStringTransformer
{
    string Transform(string input, CultureInfo culture);
}
```

With a new overload:

```csharp
        public static string Transform(this string input, CultureInfo culture, params ICulturedStringTransformer[] transformers)
        {
            return transformers.Aggregate(input, (current, stringTransformer) => stringTransformer.Transform(current, culture));
        }
```
