### ISSUE TITLE
ByteSize for French culture

### ISSUE THREAD

**Issue by rmoergeli** [Humanizr/Humanizer#1069]
Result of `ByteSize.FromBytes(7404457344)` is 6.9 GB. For French culture it should be 6.9 Go.

How to achieve?

English: "KB", "MB", "GB"

French: "Ko", "Mo", "Go"

**Comment by Orace** [comment]
As explained [here](https://fr.wikipedia.org/wiki/Octet#Multiples), the it should be "Kio", "Mio", "Gio".

**Comment by Orace** [comment]
Actually fixed with 17e98849b52fa4e3bc50d57b53f778e8a8a264f2
