### ISSUE TITLE
Can you prefix a string with "a" or "an"

### ISSUE THREAD

**Issue by dustyghost** [Humanizr/Humanizer#1091]
For example

I have "unicorn", I would like that to end up "a unicorn"
I have "hour", I would like that to end up "an hour"
I have "penguin", I would like that to end up "a penguin"

**Comment by hangy** [comment]
From my understanding, the required rules would be pretty complex (even though it's only applicable to English locales), because the prefix is based on pronunciation, so that the same word might require different prefixes in en-IE and en-GB. I'm not sure Humanizer can do this right now.

**Comment by dustyghost** [comment]
Yeah I thought so, Humanizer is pretty amazing at pluralizing, I was hoping it did this too. Never mind, will find another way.

**Comment by Arithmomaniac** [comment]
This does exist, though: https://www.nuget.org/packages/AvsAn/

**Comment by hazzik** [comment]
Would be outside of the scope for Humanizer
