### ISSUE TITLE
How to stop all cultures from being deployed to output directory?

### ISSUE THREAD

**Issue by hosseinitabar** [Humanizr/Humanizer#1109]
Hello guys.

First I want to thank you for this amazing library.

Second I noticed that after using it, I see a lot of `Humanizer.resource` dll files in a lot of directories in my output directory.

Here's a picture:

![Capture](https://user-images.githubusercontent.com/81751123/126068333-646aa42e-a085-4b02-80e7-de0eb9eabd9a.PNG)

**********

![Capture2](https://user-images.githubusercontent.com/81751123/126068332-d419933a-fa33-4de4-97d1-83d44a624089.PNG)

My question is, how can I stop these resource files from cluttering my output?

I'm using ASP.NET Core.

Thank you so much.

**Comment by hangy** [comment]
The Humanizer NuGet package alwayas pulls all languages. If you only need specific languages, you can use that specific NuGet package only: https://github.com/Humanizr/Humanizer/blob/5c3b1341d8fafaea4a9997fae03191548f9c8656/readme.md#specify-lang

**Comment by hazzik** [comment]
Install Humanizer.Core only
