### ISSUE TITLE
MetricNumeralExtensions.ToMetric is obsolete, use MetricNumeralFormats?

### ISSUE THREAD

**Issue by LeahPike** [Humanizr/Humanizer#1111]
We've upgraded 2.8.26 from to 2.11.10 and now get the following warning:

> 'MetricNumeralExtensions.ToMetric(double, bool, bool, int?)' is obsolete: 'Please use overload with MetricNumeralFormats'

Are there any examples on how to use MetricNumeralFormats, I cannot find any documentation.

This is our current code:

`.ToMetric(false, true, 2);`

**Comment by aloisdg** [comment]
@LeahPike You have to use:

```csharp
var format = MetricNumeralFormats.WithSpace | MetricNumeralFormats.UseName;
var decimals = 2;
foo.ToMetric(format, decimals);
```

source: [MetricNumeralTests](https://github.com/Humanizr/Humanizer/blob/12cc40033da9a18a19d0da419a1d39ab9ae76dba/src/Humanizer.Tests.Shared/MetricNumeralTests.cs) and [MetricNumeralFormats](https://github.com/Humanizr/Humanizer/blob/12cc40033da9a18a19d0da419a1d39ab9ae76dba/src/Humanizer/MetricNumeralFormats.cs)

As the original creator of the feature (with all the boolean), I love this choice made by the Humanizr's team. It is clearer like this :)

**Comment by LeahPike** [comment]
Thank you :)

**Comment by aloisdg** [comment]
You are welcome. I added this Q&A to stackoverflow: https://stackoverflow.com/questions/68542840/metricnumeralextensions-tometric-is-obsolete-use-metricnumeralformats/68542841#68542841
