### ISSUE TITLE
Dehumanize DateTime with reference date?

### ISSUE THREAD

**Issue by nemec** [Humanizr/Humanizer#112]
The documentation says dehumanization of dates is not reversible, but is that only because a phrase like "yesterday" is relative to some unknown reference point?

What if the API included a method like `"yesterday".DehumanizeRelativeTo(DateTime.UtcNow)` that calculated "yesterday" from the perspective of the current time? It would be really cool to be able to turn the string "set an alarm for tomorrow at two thirty" into a command + datetime-relative-to-now using the Humanize library (rather than rolling your own). I assume this idea has been visited before, were there any specific challenges that can't be solved with an explicit reference date?

**Comment by masaeedu** [comment]
@MehdiK Would you be willing to special case it for English? There have been some excellent efforts at porting libraries like Chronic to .NET (https://github.com/robertwilczynski/nChronic) but it would be great to have this integrated with an actively maintained library. I haven't looked at the internals of Humanizer, but I'm hoping it is possible to identify date keywords (e.g. yesterday/today etc.) and any prepositions/adjectives associated with them. You can see an example of how the Java natty library (https://github.com/joestelmach/natty) breaks this down here: http://natty.joestelmach.com/try.jsp.

**Comment by ThomasPe** [comment]
I came across this issue since I'm trying to understand dates from voice inputs like Alexa and Cortana. This would be really awesome, even if it could not support all languages.

**Comment by MaStr11** [comment]
@ThomasPe For voice recognition you might be better of with something like [LUIS](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/home).

**Comment by ThomasPe** [comment]
I'm actually using LUIS, but haven't found a way to do this kind of recognition.

**Comment by MaStr11** [comment]
Oh I see. But [builtin.datetime](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-entities#builtindatetime) seems like a perfect match for your use case to me.

**Comment by fahadash** [comment]
Can someone tell me where can I find this DehumanizeRelativeTo feature? I couldn't find it anywhere in codebase.
