### ISSUE TITLE
Can you "Possessive-ise" a word?

### ISSUE THREAD

**Issue by amjadkhan** [Humanizr/Humanizer#1143]
This feels trivial. 

`"Mike".Possessive() => "Mike's"` // apostrophe + 's' added to the end because noun doesn't end with an 's'
`"James".Possessive() => "James'"` // single apostrophe added to the end only because noun ends with an 's'

Thanks

**Comment by aloisdg** [comment]
What if the input is null or empty?

**Comment by amjadkhan** [comment]
Thanks for the comment @aloisdg .

**Comment by aloisdg** [comment]
My implementation is quite naïve, but should work as expected. I don't know if we should add it or not to the library.

**Comment by amjadkhan** [comment]
With an option to omit the s ? I raised this because while it is grammatically correct to use both **James'** and **James's**  the latter doesn't look familiar to me and one which I am not familiar with.

**Comment by aloisdg** [comment]
Why not :)

Be the change you want to see in the world. Do what you want with the snippet I shared.

**Comment by amjadkhan** [comment]
I might just even do that ;-)
