### ISSUE TITLE
Register our own language?

### ISSUE THREAD

**Issue by thegrahamking** [Humanizr/Humanizer#1145]
I'm in need of support for Welsh (cy), however, only for a very limited set of translations (`TimeUnit.Day` and `TimeUnit.Minute`) and Humanizer doesn't currently support Welsh.

Is it possible to register our own Welsh language support (and simply not provide the translations we don't need) or would we need to contribute a full Welsh translation and wait for the PR to be accepted in and released?

Thank you

**Comment by clairernovotny** [comment]
Hi @thegrahamking Thanks for your interest in contributing Welsh! Right now, Humanizer has a few static initialization mechanisms that hook up the localizations. A PR with Welsh would be most welcome. It doesn't need to be all done at once; Humanizer will fallback to the defaults (usually English) if there's incomplete support for a particular language, so anything you can add would be welcome.

I try to get releases to Humanizer published fairly regularly, especially when there's a new language.

**Comment by thegrahamking** [comment]
I have to admit I wasn't expecting you to be so open to parital lanaguge support, it's very refreshing to see that in the Open Source Community, thank you.

I'm not a Welsh speaker myself but we may be able to get the professional translator we'll be using for the rest of our project to translate some of the Humanizer resx and provide us with specific examples we can unit test against but I can't make any promises I'm afraid.

Fingers crossed we'll be sending you a PR for it!

**Comment by thegrahamking** [comment]
I'm afraid due to business pressures we won't be able to provide Welsh translations and, because our usage is so limited, we've had to drop humanizer.  We hope to reintroduce it at a future date.
