### ISSUE TITLE
long ToMetric()

### ISSUE THREAD

**Issue by kamilkosek** [Humanizr/Humanizer#1153]
Hello all,
my API is providing a large number as `long` which represents a price.
As of what i saw `ToMetric()` only supports ìnt`.
How could I make the numbers readable ? 
```csharp
758000000.ToMetric() => "758M$"
4900000000.ToMetric() => "4.9B$"
```

**Comment by aloisdg** [comment]
Double are supported: [source](https://github.com/Humanizr/Humanizer/blob/7e20c402fa9f1e1bee889bec2f34703743f603c9/src/Humanizer/MetricNumeralExtensions.cs#L210)

**Comment by kamilkosek** [comment]
Ah thanks, that was the missing piece 👍

**Comment by aloisdg** [comment]
We could see to support other numeric type one day.
