### ISSUE TITLE
"IpRightRecordalStatus".Singularize() becomes "IpRightRecordalStatu"

### ISSUE THREAD

**Issue by kzendra** [Humanizr/Humanizer#1163]
Hi
I'm using Humanizer.Core 2.11.10 to fix properties name from request for generic usage in SQL queries (inherited from several devs, list properties can have plural or singular names, so all are sent through Humanizer). 
This one fails as it cut the s at the end of the singular version of the name...

**Comment by hazzik** [comment]
""IpRightRecordalStatus".Singularize(inputIsKnownToBePlural: false)` should do the trick.

**Comment by kzendra** [comment]
That presumes I will know in advance if the string is singular or plural. And as strings are dynamic and unknown, so this does not solve the basic issue.

**Comment by hazzik** [comment]
The parameter `false`, presumes the opposite: that you don’t know if word is plural or singular. The default (`true`) assumes that you do know.
