### ISSUE TITLE
Spanish Localization Issues and Improvements - ToWords()

### ISSUE THREAD

**Issue by ohmineer** [Humanizr/Humanizer#1166]
Hi, 
I checked the accuracy of Spanish localization, and I found some issues I would like to fix through a PR.
I have been already working on it and it is almost ready. You can follow my work [in this public fork](https://github.com/ohmineer/Humanizer). This is the first of a handful issues, that I will describe separately, my fork will try to address.

# 1. long.ToWords()
## 1.1. WARNING: Implementation is for int numbers
Current implementation casted the long number into and int number.
For numbers greater than `int.MaxValue` or lower than `int.MinValue`, NotImplementedException() is thrown. As a user of the library, I wouldn't expect this sort of method to produce an exception. In my opinion, behavior should mimic ToString() which always provides a value.

### 1.1.1. PROPOSAL
Provide an implementation for the full range of long numbers.

### 1.1.2. FAILING TEST
````CSharp
[Theory]
[InlineData(1111111111111, "un billón ciento once mil ciento once millones ciento once mil ciento once")]
public void ToWords(long number, string expected, GrammaticalGender gender = GrammaticalGender.Masculine)
{
    Assert.Equal(expected, number.ToWords(gender));
}
````
````PowerShell
System.NotImplementedException : The method or operation is not implemented.
````

### 1.2.1. PROPOSAL
Fix the issue. See error and expected value below.

### 1.2.2. FAILING TEST
````CSharp
[Theory]
[InlineData(1001111111, "mil un millones ciento once mil ciento once")]
[InlineData(1002000001, "mil dos millones uno")]
public void ToWords(long number, string expected, GrammaticalGender gender = GrammaticalGender.Masculine)
{
    Assert.Equal(expected, number.ToWords(gender));
}
````
````PowerShell
Assert.Equal() Failure
              ↓ (pos 4)
Expected: mil un millones ciento once mil ciento once
Actual:   mil millones un millón ciento once mil ciento···
              ↑ (pos 4)
````
````PowerShell
Assert.Equal() Failure
              ↓ (pos 4)
Expected: mil dos millones uno
Actual:   mil millones dos millones uno
              ↑ (pos 4)
````

## 1.3. ERROR: Numbers ended in 1 should have a special treatment

>  @clairernovotny , please read this as I need feedback on the proposals. Thanks in advance.

Number 1 in Spanish can be written as `un` or `uno` depending on the position of the noun. We say `un millón` for `one million`, `cincuenta y un mil` for `fifty thousand` but `cincuenta y uno` for `fifty one`.

See below current behavior.

### 1.3.1. PROPOSAL(S)
Fix the error.

**IMPORTANT NOTE** 
There is a couple of approaches I took to overcome the issue:
- The first approach is using `GrammaticalGender.Neuter` as a switch to be able to produce masculine `un` or `uno` as required.
    This is just a workaround as there is not a `GrammaticalGender.Neuter` in Spanish language. Both forms of the word are 
    `GrammaticalGender.Masculine`. I started implementing this way but decided it was not correct as it feels unnatural.
    This commit [5213a44b174111fc46a7fd98bf894bdebc3619c1](https://github.com/ohmineer/Humanizer/tree/5213a44b174111fc46a7fd98bf894bdebc3619c1) has all the issues described above 
    solved and uses the workaround to solve the need described. It passes all tests so technically it would be a PR candidate.

- The second approach would introduce new methods in the public API with a new parameter `wordForm` of type WordForm (enumeration). This new parameter would allow us to produce form `un` when it is set to `WordForm.Abbreviation` and form `uno` when it is set to `WordForm.Normal`.  It would not be a breaking change but an addition to the existing public API.
    In my opinion, this approach is more appropriate.  However, the problem is `ApiApprover` test fail and I suspect this needs to be discussed. In any case, my fork is now updated and uses this [approach](https://github.com/ohmineer/Humanizer/tree/improve-spanish). I provide test coverage for the new methods as I will describe in the PR if this proposal goes ahead.
    I am not sure whether other languages would benefit from this new parameter. In Spanish, this parameter would be needed in `ToOrdinalWords()` and `Ordinalize()` extensions as numbers ended in 1 and 3 present similar variations to the one described above.
 Furthermore, this new `WordForm` enumeration may add options for a future feature which would produce different forms of the same word (i.e. abbreviation, acronym, shortenings, contractions.

### 1.3.2. FAILING TEST
````CSharp
[Theory]
[InlineData(1, "mil un millones ciento once mil ciento once", GrammaticalGender.Neuter)]
[InlineData(21000, "mil dos millones uno")]
[InlineData(31501, "treinta y un mil quinientos uno")]
public void ToWords(long number, string expected, GrammaticalGender gender = GrammaticalGender.Masculine)
{
    Assert.Equal(expected, number.ToWords(gender));
}
````
````PowerShell
Assert.Equal() Failure
            ↓ (pos 2)
Expected: un
Actual:   uno
            ↑ (pos 2)
````
````PowerShell
Assert.Equal() Failure
                ↓ (pos 6)
Expected: veintiún mil
Actual:   veintiuno mil
                ↑ (pos 6)
````
````PowerShell
Assert.Equal() Failure
                      ↓ (pos 12)
Expected: treinta y un mil quinientos uno
Actual:   treinta y uno mil quinientos uno
                      ↑ (pos 12)
````

Thanks for reading this long issue.

**Comment by clairernovotny** [comment]
Hi, thanks for jumping in on this. I agree that the second option makes more sense. Fixing the ApiApprover tests are generally a matter of taking the generated output from the diff and putting it into the original source text file. That will enable the test to pass and shows a consolidated public API diff in the PR.
