### ISSUE TITLE
Spanish localization issues and improvements - DateTime/DateOnly.ToOrdinalWords(), TimeOnly.ToClockNotation, TimeSpan.Humanize()

### ISSUE THREAD

**Issue by ohmineer** [Humanizr/Humanizer#1169]
Hi again,

Third and final post (after #1166 and #1168) with issues around Spanish localization. I hope to be able to provide a fix with the proposals soon.

# 1. DateTime.ToOrdinalWords() and DateOnly.ToOrdinalWords()
## 1.1. ERROR: Date ordinalization in Spanish is not common
We don't normally ordinalize dates in Spanish. Saying `20º febrero 2020` would be wrong to my knowledge. The correct way of saying a date in Spanish is just `20 de febrero de 2020`. Exceptionally, some special days may be ordinalized such as `1º de mayo` (Spanish Labour Day) but it is much more common the other form in normal speech.

I commented it [here](https://github.com/Humanizr/Humanizer/issues/1012#issuecomment-883369768). 

## 1.2. PROPOSAL
`DateTime/DateOnly.ToOrdinalWords()` extension may not have sense in Spanish and it would be better just a `ToWords()`. However, I understand Humanizer should be consistent among different localizations. Therefore, I propose these methods return the standard way in which dates are expressed in Spanish.

## 1.3. FAILING TEST
````CSharp
[Fact]
public void OrdinalizeString()
{
    Assert.Equal("25 de enero de 2022", new DateTime(2022, 1, 25).ToOrdinalWords());
}
````
````PowerShell
Assert.Equal() Failure
            ↓ (pos 2)
Expected: 25 de enero de 2022
Actual:   25.º enero 2022
            ↑ (pos 2)
````

# 2. TimeOnly.ToClockNotation()
## 2.1. ENHANCEMENT: This extension is not implemented for Spanish yet
Implement `TimeOnly.ToClockNotation()` in Spanish as [proposed by The Royal Spanish Academy RAE](https://www.rae.es/dpd/hora).
Please note, The Royal Spanish Academy recommends clarification of the period of the day when a 12-hour clock system is used and you don't have any other context to determine it. For that reason, my proposed implementation would return:
- 10:30 -> las diez y media de la mañana (Half past ten in the morning)
- 22:30 -> las diez y media de la noche (Half past ten in the night)

# 3. TimeSpan.Humanize()
## 3.1. ENHANCEMENT: Tests for Spanish localisation are too simple.
As it is shown below, more complex tests reveal inaccurate translations.

### 3.1.1. PROPOSAL
Copy and adapt tests from English locale to improve test coverage and detect innacuracies.

## 3.2. ERROR: `TimeSpan.Humanize()` mixes numbers and words disregarding `towords` parameter.
It is expected that number format is kept when `towords = false`.

### 3.2.1. FAILING EXAMPLE 1
````Csharp
[Theory]
[InlineData(1, "1 milisegundo")]
public void Milliseconds(int ms, string expected)
{
	var actual = TimeSpan.FromMilliseconds(ms).Humanize();
	Assert.Equal(expected, actual);
}
````
````Shell
Assert.Equal() Failure
          ↓ (pos 0)
Expected: 1 milisegundo
Actual:   un milisegundo
          ↑ (pos 0)
````
### 3.2.2. FAILING EXAMPLE 2
````CSharp
[Theory]
[InlineData(365 + 365, "1 año, 11 meses, 29 días")]
public void Year(int days, string expected)
{
	var actual = TimeSpan.FromDays(days).Humanize(precision: 7, maxUnit: TimeUnit.Year);
	Assert.Equal(expected, actual);
}
````
````PowerShell
Assert.Equal() Failure
          ↓ (pos 0)
Expected: 1 año, 11 meses, 29 días
Actual:   un año, 11 meses, 29 días
          ↑ (pos 0)
````
### 3.2.3. PROPOSAL
Fix these issues by completing the translation in Spanish .resx file.

### 3.3.1. FAILING EXAMPLE
````CSharp
[Theory]
[InlineData(0, 0, 1, 1, 2, "un minuto, un segundo")]
[InlineData(1, 2, 3, 4, 4, "un día, dos horas, tres minutos, cuatro segundos")]
public void ComplexTimeSpan(int days, int hours, int minutes, int seconds, int precision, string expected)
{
	var timeSpan = new TimeSpan(days, hours, minutes, seconds);
	Assert.Equal(expected, timeSpan.Humanize(precision, toWords: true));
}
````
````PowerShell
Assert.Equal() Failure
          ↓ (pos 0)
Expected: un minuto, un segundo
Actual:   one minute, one second
          ↑ (pos 0)

Assert.Equal() Failure
          ↓ (pos 0)
Expected: un día, dos horas, tres minutos, cuatro s···
Actual:   one day, dos horas, tres minutos, cuatro ···
          ↑ (pos 0)
````

### 3.3.2. PROPOSAL
Fix these issues by completing the translation in Spanish .resx file.

## 3.4. ENHANCEMENT: Collection formatter *&* is not ideal for Spanish language
It does not make sense to use `&` in Spanish. It is supposed to be the abbreviation of latin `et`. However, we have a shorter form of appending sentences, the conjunction `y`. See reference: [símbolo «&»](https://www.fundeu.es/consulta/el-simbolo/)

### 3.4.1. FAILING EXAMPLE
````CSharp
[Theory]
[InlineData(86401200, 2, "1 día y 1 segundo")]
public void TimeSpanWithPrecisionAndAlternativeCollectionFormatter(int milliseconds, int precision,
    string expected, bool toWords = false)
{
    var actual = TimeSpan.FromMilliseconds(milliseconds).Humanize(precision, collectionSeparator: null, toWords: toWords);
    Assert.Equal(expected, actual);
}
````
````PowerShell
Assert.Equal() Failure
                    ↓ (pos 10)
Expected: 2 semanas y 1 día
Actual:   2 semanas & un día
                    ↑ (pos 10)
````

### 3.4.2. SOLUTION
Replace the collection formatter *&* by the conjunction *y*.

## 3.5. ENHANCEMENT: `TimeSpan.Zero()` should be "nada" when parameter toWords:true.
As it is often heard in spoken Spanish: ¿Cuánto tiempo te costó terminar esa tarea? No me costo "nada". 
I believe this would be equivalent to the value English localization returns: `no time`.

````CSharp
[Fact]
public void NoTimeToWords()
{
	Assert.Equal("nada", TimeSpan.Zero.Humanize(toWords: true));
}
````
````PowerShell
Assert.Equal() Failure
          ↓ (pos 0)
Expected: nada
Actual:   0 segundos
          ↑ (pos 0)
````

**Comment by ohmineer** [comment]
Hi @clairernovotny, thanks for assigning me these issues. As a comment, implementing fixes/enhancements described in this last issue may be considered 'opinionated' so I would not mind discussing it with other Spanish speakers. In any case, I believe my proposals are quite common, at least in Spain and the region I live.

**Comment by clairernovotny** [comment]
@ohmineer Always happy to have help with localization from native language speakers! Humanizer could not exist without everyone's collaboration :)

I'll tweet out a link to this thread to get more 👀 on it.

**Comment by jesulink2514** [comment]
As a native Spanish speaker, I agree with everything @ohmineer has stated.

**Comment by carlosmunozrodriguez** [comment]
@clairernovotny I'm coming form your tweet :)
Actually I'm not sure about 3.5, There may be other ways to say it depending on the country. To me it seems correct but there could be other opinions. The rest looks good to me.

**Comment by ohmineer** [comment]
Thanks @jesulink2514 and @carlosmunozrodriguez for your opinions.

Regarding 3.5, do you know any other equivalent expression that is used either in Spain or other countries?

I thought too much about this but I wasn't able to find anything better or anything that sounded more natural for the original English expression "no time". 

The other options I came up with were too formal or weird. These are some examples I had after consulting RAE and Fundeu websites: Tiempo/periodo/lapso cero/nulo/ínfimo/despreciable.

Then I asked myself how I would answer a related question and I decided "nada" is the word I would always use. Examples "No te preocupes, no tardo nada" or "tengo fibra óptica, las páginas cargan en nada!!".

Please, do let me know if you find any other good option.
