### ISSUE TITLE
The resource object with key 'DateHumanize_MultipleDaysAgo' was not found (Parameter 'resourceKey')

### ISSUE THREAD

**Issue by rborosak** [Humanizr/Humanizer#1170]
I'm getting an exception above when using "hr" culture. 
I get the same exception no matter if I use Humanizer.Core.hr package or entire Humanizer package. 

As far as I can see the resource exists. 

Is there any workaround?

**Comment by rborosak** [comment]
The exception message is wrong. 
I have added some test in your source which are failing. Humanizer is actually looking for DateHumanize_MultipleDaysAgo_DualTrialQuadral  resource which is not present

**Comment by clairernovotny** [comment]
Thanks @rborosak. Can you please submit a PR with the failing test and hopefully a fix?

**Comment by rborosak** [comment]
@clairernovotny I have cloned the repo and created a local branch. I have fixed the issue but I cannot publish a branch to Humanizer repo.

 I get an error "It looks like you don't have write access to humanizr/Humanizer. If you should, please check with a repository administrator.
 
 Please help :)
