### ISSUE TITLE
Support bitrate network speeds

### ISSUE THREAD

**Issue by jazzmanro** [Humanizr/Humanizer#1182]
Hi there, I don't have much experience with Humanizer so maybe I can't find it but it would seem there is no way currently to present data rates int bits/s as they are usually presented when talking about network speed. It's not 1MB/s like it is supported here but 8mbps or 8mbit, etc.

Is there a way currently to output bitrates using Humanizer or it is not implemented yet?

**Comment by DocBrown101** [comment]
I just noticed the same thing, is there a solution for this?

**Comment by SimonCropp** [comment]
No this is not implemeted
