### ISSUE TITLE
Humanize no translated for "zh-CN"

### ISSUE THREAD

**Issue by lisenz** [Humanizr/Humanizer#1229]
`var text = DateTime.UtcNow.AddHours(-2).Humanize(null, null, new CultureInfo("zh-CN"));`

This code does not return Chinese. 
where is it wrong?

Possibly translation:
 2 hours ago   2小时前

**Comment by hangy** [comment]
Do you have the `Humanizer.Core.zh-CN` package installed? I did [a quick test on .NET Fiddle](https://dotnetfiddle.net/yFiASv), which correctly(?) outputs "2 小时前"
```csharp
using System;
using System.Globalization;
using Humanizer;

public class Program
{
	public static void Main()
	{
		var text = DateTime.UtcNow.AddHours(-2).Humanize(null, null, new CultureInfo("zh-CN"));
		Console.WriteLine(text);
	}
}
```

**Comment by lisenz** [comment]
@hangy 
I did not install the Humanizer.Core.zh-CN package，I thought it was included in Humanizer.Core
it's OK now，thank you！

**Comment by hangy** [comment]
> @hangy 
> I did not install the Humanizer.Core.zh-CN package，I thought it was included in Humanizer.Core
> it's OK now，thank you！

Glad to hear that helps! FWIW, you can just install the Humanizer package to get all locales.
