### ISSUE TITLE
[Question] Use within blazor app

### ISSUE THREAD

**Issue by lonix1** [Humanizr/Humanizer#1233]
I've used this library before, many times, without a care for how it works... because "it just works". But now I'm considering using it in a blazor app, so I'm obviously concerned about the app's final size.

Does it use some sort of dictionary - for example, for pluralising / singularising strings, and irregular verbs? (I ask because a dictionary would obviously inflate the app's size.)

**Comment by SimonCropp** [comment]
You should leverage trimming for this
