### ISSUE TITLE
Compilation fails on the very latest Visual Studios due to character-encoding problem

### ISSUE THREAD

**Issue by vilinet** [Humanizr/Humanizer#1245]
We have found this issue when using the latest VS: https://github.com/xamarin/xamarin-android/issues/7447
And one of the issue the xamarin team found that there is a strange char in the code:
https://github.com/Humanizr/Humanizer/blob/7f80e03070f9e46cb5bc499567a95e0f54b4bdb5/src/Humanizer/Localisation/NumberToWords/GreekNumberToWordsConverter.cs#L187

That "B" char i think is being the Greek Beta char, and we were told to fix that as it is being somehow a not liked char by the compiler.

**Comment by SimonCropp** [comment]
Pr mereged
