### ISSUE TITLE
Humanizer.Core.fil-PH is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by MarkIvanDev** [Humanizr/Humanizer#1253]
Installing Humanizer.Core.fil-PH triggers the error NU1202: Package Humanizer.Core.fil-PH is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Humanizer.Core.fil-PH does not support any target frameworks.

I have also checked the nuspecs for the other languages and nothing seems to be amiss with the fil-PH locale. And I have also tried making a fil-PH satellite assembly with a new project and it also triggers this error.

Is there a workaround for this? Or is this a known problem with nuget? Thank you

**Comment by SimonCropp** [comment]
the package seems correct. so i assume it is a nuget tooling issue

![image](https://github.com/Humanizr/Humanizer/assets/122666/f2ec228e-11fe-41cf-a021-30c300598314)
