### ISSUE TITLE
Persian Language request

### ISSUE THREAD

**Issue by MuhammadAshouri** [Humanizr/Humanizer#1259]
This is a great project but it's missing Persian. I hope you can add this and make this project absolute perfect.

**Comment by hangy** [comment]
There are a handful of Farsi translations in https://github.com/Humanizr/Humanizer/blob/23c4c2a526deb0f101b39fe060fca66f5e66c823/src/Humanizer/Properties/Resources.fa.resx. This project relies heavily on community contributions to add support for new languages, so the best way to get better support for the Persian Language might be to open a PR. 😊

**Comment by SimonCropp** [comment]
closing this. happy to consider a PR
