### ISSUE TITLE
decimal to percentage string

### ISSUE THREAD

**Issue by mulei2023** [Humanizr/Humanizer#1295]
could not find any usage for transforming a decimal to readable percentage string

eg:
0.48 -->48%
0.3754->37.54%

**Comment by etherfield** [comment]
Workaround: `0.48.Hundreds() + "%"`

**Comment by hangy** [comment]
```csharp
0.48.ToString("P0");
```
Will do the same and should do better with localization

**Comment by hazzik** [comment]
Closing as per @hangy
