### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by ogix** [Humanizr/Humanizer#1303]
The last release was made almost 2 years ago what is actually a long term.. It is pity as there are no alternatives (or I don't know yet). Latest releases were made by @clairernovotny. Could you please or anyone else from maintainers tell what the status is and if we can expect a new release soon? Thanks.

**Comment by aloneguid** [comment]
I'm also interested in this. Humanizer is one of the most important libraries I use, so if it's not maintained we should start thinking of forking it and start merging PRs.

**Comment by SimonCropp** [comment]
@hazzik @clairernovotny @MehdiK can i join the Humanizer team?

**Comment by andrewimcclement** [comment]
The latest version on nuget is 2.14.1 which is much earlier than the badge reports from Azure DevOps (2.14.27). Perhaps new versions are not being published to nuget and/or the code is not being maintained here any more?

**Comment by ChrisSfanos** [comment]
Hi @MehdiK @clairernovotny @hazzik @mexx  - input here?  It does look like the project doesn't have many commits in the last year.  Are the 4 of you still active maintainers?

**Comment by SimonCropp** [comment]
@ChrisSfanos given there was no response from December, https://github.com/Humanizr/Humanizer/issues/1303#issuecomment-1859450982 
i am not really expecting a response now

can we set a deadline on this?

**Comment by ChrisSfanos** [comment]
I have a regular meeting with a set of Foundation team members on Wednesday and we are going to discuss it there.

**Comment by SimonCropp** [comment]
@ChrisSfanos want me to join the meeting?

**Comment by ChrisSfanos** [comment]
Hi @SimonCropp - probably not needed.  The conversation would be around the mechanics of this and not the validity of your request

**Comment by hazzik** [comment]
I just want to clarify: I have only limited rights for this exact repo, nothing more. Theoretically, I can continue merging the pending PRs and fix some issues. But I’m not able to make releases, or push to NuGet, not have access to any other infrastructure. So instead of helping, in my mind, it would create a false sense that library is still alive, which is not.

**Comment by ChrisSfanos** [comment]
Thanks @hazzik for the background info - very helpful.  A couple of questions/thoughts:
1) Who DOES have access to the infrastructure for new releases via NuGet etc?
2) One of the goals of the Foundation is to help people projects going if the original maintainers no longer wish to continue working on it - if @SimonCropp is volunteering to take over 'ownership' of the project going forward, I feel we should be try our best to make that happen

Thanks!

**Comment by hazzik** [comment]
@ChrisSfanos I believe that @clairernovotny might be the only one who has access to everything as for now. A lot of infrastructural and tools changes happened since @MehdiK handed over the project so they would not have access to everything although being a creator of the library. And I think @mexx has about the same rights in the project as me.

**Comment by SimonCropp** [comment]
just to be clear i am "volunteering to take over 'ownership' of the project going forward"

but if any of the exiting owners ever want to become active again, and would prefer to take sole ownership, i am happy to back out at any point. or stay on if desired

**Comment by SimonCropp** [comment]
@ChrisSfanos  outcome?

**Comment by ChrisSfanos** [comment]
We chatted about it today - couple of paths being discussed.  I've reached out to Claire directly to get an understanding on her plans (if any) for the project.  Option 1 is a hand over of the tools/NuGet/etc to you for a (seamless) transition.  Option 2 is for you to fork the project and launch a "Humanizer v2" and go from there.  We would work with you in that case to on-board the project to the .NET Foundation (technically it's a new project) and go from there.  I'll keep you in the loop on what I hear back

**Comment by clairernovotny** [comment]
Hey, sorry, been really busy lately -- I should have a bit more time to get some PRs reviews merged and releases out in the next month or so.

**Comment by SimonCropp** [comment]
@clairernovotny awesome. 

especially since in my recent dives in the codebase, it is clear i am lacking some domain knowledge in a few areas

i am still happy to come on board if u want help reviewing prs and triaging issues

**Comment by andrewimcclement** [comment]
That might be a good argument to avoid a single point of failure? Obviously it's fine for @clairernovotny to be busy, but ideally we should have a second person who has the appropriate permissions to create releases etc., so the burden isn't entirely on one person?

**Comment by ogix** [comment]
[like]  Olegas Gončarovas reacted to your message:
________________________________

**Comment by MehdiK** [comment]
Hi all, my apologies for the delayed response here. I will admit I haven't spent any time on this library in the past couple of years. @SimonCropp, it would be amazing to have you as a contributor. That would give us a bit more redundancy when the existing contributors are unavailable. I just sent you an invite.

**Comment by MehdiK** [comment]
@clairernovotny , it would be great to give more folks access to release changes. It doesn't have to be many people; but folks like @hazzik / @mexx are long time contributors to the codebase and know the library really well, and @SimonCropp is a steady and trusty pair of hands who's been using the library for a long time and would be a great addition.

Let's light some fire under the project and grow the community around it.

**Comment by TheCodingOwl** [comment]
If this is becoming active again, I have PRs I would like to start putting in. I have a lot of local perf improvements and benchmarks. I'll keep an eye on how you guys want to handle stuff moving forward since they're TFM specific.

**Comment by SimonCropp** [comment]
@TheCodingOwl curious on the specific tfm features you want to add?

**Comment by SimonCropp** [comment]
@MehdiK can you make me an org admin

**Comment by SimonCropp** [comment]
@MehdiK @clairernovotny can you also make me ad admin of the devops project. so i can deploy a beta

**Comment by MehdiK** [comment]
Made you admin @SimonCropp . I don't believe I have access to the devops project. cc @clairernovotny

**Comment by SimonCropp** [comment]
@MehdiK thanks

**Comment by SimonCropp** [comment]
@MehdiK @clairernovotny any progress on getting me devops access?

seems claire is still the only one who can deploy

![image](https://github.com/Humanizr/Humanizer/assets/122666/bf680b7e-2151-4e67-959e-90ae6b366738)

**Comment by clairernovotny** [comment]
lets sync here -- I haven't left here.

**Comment by SimonCropp** [comment]
@clairernovotny sounds awesome. I am at simon.cropp@gmail.com

and probably worth including @hazzik
