### ISSUE TITLE
Should fix and extend the pluralization rules (WAS: Consider using built in .NET for underlying pluralization)

### ISSUE THREAD

**Issue by ghost** [Humanizr/Humanizer#142]
The built in .NET PluralizationService has more work done in correctly pluralizing most of English. Please consider using this as the service behind the Pluralize feature of Humanizer.

http://referencesource.microsoft.com/#System.Data.Entity.Design/Entity/Design/PluralizationService/EnglishPluralizationService.cs

I realize it is in an assembly you probably do not want to require as a dependency, but perhaps some notes can be taken from it.

**Comment by SimonCropp** [comment]
seems nothing to action here
