### ISSUE TITLE
TimeSpan Humanize ignored toWords: false parameter

### ISSUE THREAD

**Issue by BloodShadow174** [Humanizr/Humanizer#1444]
When executing the code:
```csharp
var oneDay = TimeSpan.FromDays(1);

oneDay.Humanize(
    culture: CultureInfo.GetCultureInfo("ru"),
    toWords: false
);
```
Result:
"один день"
Instead of the expected result:
"1 день"

This result is not only in Russian localization, but also in many others!
I think that you still need to take into account the toWords parameter with a single value, most likely you can fix it here:
https://github.com/Humanizr/Humanizer/blob/c915898b9ebf5b0ddde2384b284f02896cd29e11/src/Humanizer/Localisation/ResourceKeys.TimeSpanHumanize.cs#L27

P.S. Congratulations to everyone on the fact that the library has begun to be updated again 🥰

**Comment by SimonCropp** [comment]
can you submit a pull request to fix the issue?

**Comment by BloodShadow174** [comment]
> can you submit a pull request to fix the issue?

I think I can
