### ISSUE TITLE
Pluralize/Singularize - Process

### ISSUE THREAD

**Issue by VagyokC4** [Humanizr/Humanizer#1495]
When I Singularize the word "process" I get back "proces" which is incorrect.

**Comment by hazzik** [comment]
We have test for this word:
https://github.com/Humanizr/Humanizer/blob/9dafc05e0425591c4b6e73e6769a55a224c4dcb2/src/Humanizer.Tests/InflectorTests.cs#L161
The test has been there for at least 10 years.

Also, "process" is already singular and trying to make it more singular does not help. If you don't know that the word is singular or plural and want to get a singular word you need to pass `inputIsKnownToBePlural: false` parameter to the `Singularize` method.:

```csharp
"process".Singularize(inputIsKnownToBePlural: false)
```

**Comment by hazzik** [comment]
Please check in README: https://github.com/Humanizr/Humanizer?tab=readme-ov-file#singularize
