### ISSUE TITLE
Convert month number to text. Ex: 1 = "January"

### ISSUE THREAD

**Issue by Camilo716** [Humanizr/Humanizer#1496]
Is there a way to convert a month number to its text equivalent using Humanizer? for example 1 = "January", 2 = "February" and so on. If not, I think it would be a good feature to add.

**Comment by Camilo716** [comment]
I was not aware of this approach, in this case this issue can be closed. Thank you so much!

**Comment by SimonCropp** [comment]
glad to hear u have a way forward
