### ISSUE TITLE
Latest Beta 13 is still not compatible with .net 8

### ISSUE THREAD

**Issue by VZhangTylerTech** [Humanizr/Humanizer#1500]
Let me know if there is a workaround or new version release date. Thank you.

**Comment by hangy** [comment]
Do you have a specific error message that you could report? Pretty sure it's compatible with .NET 8 in general, as the [unit tests are run with .NET 8](https://github.com/Humanizr/Humanizer/blob/82822a9af9b63be42ea8a6887443ff6a9cdde5f3/src/Humanizer.Tests/Humanizer.Tests.csproj#L3), and a quick [.NET Fiddle](https://dotnetfiddle.net/D7rEU1) with v3.0.0-beta.13 also runs.

**Comment by frasermclean** [comment]
Seems to work fine for me to on .NET 8
