### ISSUE TITLE
The Enum Humanizer Conversion to its Description not working on .Net 7  Project

### ISSUE THREAD

**Issue by Sudheesh-TalentzQ** [Humanizr/Humanizer#1511]
I tried with both new **.Net7 and .Net8 Projects** by creating an **_enum_**  and giving it a description, while it works perfectly on .Net8 it is throwing error in .Net7 Project 

![Screenshot (27)](https://github.com/Humanizr/Humanizer/assets/149455287/bb27f49d-77b4-4ad8-9f11-dbf6d54be454)

Is there any way to fix this issue in .Net7

**Comment by SimonCropp** [comment]
@Sudheesh-TalentzQ can u try the current beta version?

**Comment by Sudheesh-TalentzQ** [comment]
@SimonCropp I'm using the latest version.

**Comment by Sudheesh-TalentzQ** [comment]
Sorry i Accidently Closed the issue

**Comment by SimonCropp** [comment]
can u share a minimal repro

**Comment by Sudheesh-TalentzQ** [comment]
[Humanizer.zip](https://github.com/Humanizr/Humanizer/files/15498995/Humanizer.zip)

**Comment by SimonCropp** [comment]
looks like a problem with the nuspec. i have fixed it here https://github.com/Humanizr/Humanizer/pull/1513

in the short term an explicit reference should fix it

```
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
```

**Comment by Sudheesh-TalentzQ** [comment]
Thank you @SimonCropp  , That fixed it

**Comment by gregoriusus** [comment]
> Thank you @SimonCropp , That fixed it

But, can you translate/localize Enums?
