### ISSUE TITLE
Drop netstandard 1.0 support

### ISSUE THREAD

**Issue by MichaelSimons** [Humanizr/Humanizer#1530]
Starting in .NET 9, a build warning is emitted if your project targets .NET Standard 1.x. For more information, see [Warning emitted for .NET Standard 1.x targets](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/9.0/netstandard-warning).  This was done because there are [downsides of targeting Net Standard 1.x](https://github.com/dotnet/designs/blob/main/accepted/2024/net-standard-recommendation.md#what-is-the-downside-of-targeting-net-standard-1x).

The .NET project has a dependency on Humanizer, therefore it is included in the .NET build dependency graph when "source building" for inclusion in Linux distros. We are trying to remove all of our .NET Standard 1.x references.  We have currently "patched" the humanizer we build to remove the .NET Standard 1.x references but would like to upstream the change if you are open to it.

**Comment by hangy** [comment]
@MichaelSimons `netstandard1.0` has already been dropped for the next release, along with some old .NET Framework versions:

- #1322
- #1482

There's a beta version on NuGet, which you could have a look at: https://www.nuget.org/packages/Humanizer.Core.de/3.0.0-beta.54#supportedframeworks-body-tab Also see [supported framework](https://github.com/Humanizr/Humanizer/blob/1dee67d72d53282aff76be8a2aaacc4a28ea6cbf/readme.md#supported-frameworks).

**Comment by MichaelSimons** [comment]
@hangy - That's great - I should have checked. Looking forward to the 3.0.0 release.

**Comment by hangy** [comment]
You're good 😊 All kudos go to @SimonCropp anyways 😉
