### ISSUE TITLE
Combine components under Localisation namespace by language rather than by component type

### ISSUE THREAD

**Issue by hazzik** [Humanizr/Humanizer#206]
/Humanizer/Localisation/

    /Humanizer/Localisation/ar/ArabicFormatter
    /Humanizer/Localisation/ar/ArabicNumberToWordsConverter

    /Humanizer/Localisation/ru/RussianFormatter
    /Humanizer/Localisation/ru/RussianNumberToWordsConverter
    /Humanizer/Localisation/ru/RussianGrammaticalNumber
    /Humanizer/Localisation/ru/RussianGrammaticalNumberDetector

etc

**Comment by onovotny** [comment]
Is this still in scope for v2? I'd like to get a beta out by the end of the month as the current dev branch adds CoreCLR support.

**Comment by MehdiK** [comment]
When we were discussing this solution layout, I have very vague recollection but from the memory some things didn't quite fit into the proposed solution. Not that they do in the current structure but I guess my point is that this solved one problem and introduced another one. So I'm torn on it. I'd vote to keep it as is if we don't have a strong argument for this structure. Thoughts?

**Comment by onovotny** [comment]
I don't have any strong thoughts on this. There's something to be said for both sides. As far as I can see, aside from the interfaces/abstract base classes, the actual localization implementations are all internal, so moving it around should not be a breaking change.

**Comment by onovotny** [comment]
I'm closing this out, leaving things as-is for now. We can revisit if there's reason to later.
