### ISSUE TITLE
Estimated frequency as string

### ISSUE THREAD

**Issue by MehdiK** [Humanizr/Humanizer#260]
"roughly every 10 weeks", "once off", "daily"

**Comment by SimonCropp** [comment]
@MehdiK still think this is worthwhile?

**Comment by MKEventsAir** [comment]
We couldn't agree on the API or the output. There hasn't been any request for it either. It was an idea that didn't prove useful. Happy to close.

**Comment by SimonCropp** [comment]
ok. thanks. will close for now
