### ISSUE TITLE
.ToWords() support for TimeSpan and DateTime

### ISSUE THREAD

**Issue by keichinger** [Humanizr/Humanizer#290]
Hey,

while browsing the examples I figured it'd be be useful to have an overload for `TimeSpan.Humanize()` that prints each unit as words, just like `.ToWords()` does.

So the following code...

``` csharp
TimeSpan.FromDays(1).Humanize()
TimeSpan.FromDays(2).Humanize()
TimeSpan.FromDays(23).Humanize()
```

should print:

```
one day
two days
twenty-three days
```

Any opinions on this topic?

**Comment by stefan-pacurar** [comment]
I would like to work on this one

**Comment by stefan-pacurar** [comment]
Oh .. it doesn`t work on win 7 :( (linq directivemissing)

**Comment by hazzik** [comment]
Covered by #405

**Comment by SimonCropp** [comment]
this has been done
