### ISSUE TITLE
Ordinal number suffixes

### ISSUE THREAD

**Issue by aaronpowell** [Humanizr/Humanizer#328]
It'd be useful to be able to get just the ordinal suffix, so `st`, `nd`, `rd`, `th` for numbers, especially when working with dates.

Use case:

``` csharp
Assert.That("20th August 2014", Is.EqualTo(new DateTime(2014, 8, 20).<something>());
```

**Comment by onovotny** [comment]
Merged in https://github.com/Humanizr/Humanizer/commit/3d71fd90cb7fb45028b9697557ec69358d3366cd
