### ISSUE TITLE
Link to http://humanizr.net/ in the repo description results in a 404 page

### ISSUE THREAD

**Issue by texhex** [Humanizr/Humanizer#368]
Link to http://humanizr.net/ in the repo description results in a 404 page from GitHub. Maybe broken gh-pages repo? 

Definitely a low priority issue, but I thought you might want to know that.

Best regards,
-Michael

**Comment by MehdiK** [comment]
I've manually revived the humanizr.net for now (by committing the CNAME into gh-branch!). The github pages used to be a lot smaller before the recent changes. 

We need to automate this process for future readme changes.

Thanks guys.

**Comment by texhex** [comment]
Thanks and you're welcome.

**Comment by mexx** [comment]
@MehdiK we could migrate the build script to [FAKE](https://fsharp.github.io/FAKE). It provides a support for updating `gh-pages` branch as part of the build. Might be an option.

**Comment by MehdiK** [comment]
That's an interesting idea @mexx; but I don't really want to update the branch on a build. In fact it's almost orthogonal to the build event. The gh-pages should be updated anytime there is a change on the readme file which in a lot of cases doesn't require a release. I haven't thought about this properly but this looks more like a task for web hooks.
