### ISSUE TITLE
Add option to humanize date and timespan in certain context

### ISSUE THREAD

**Issue by dmytro-ielkin** [Humanizr/Humanizer#412]
When I humanize zero time timespan it shows 'no time' but sometimes it makes more sense to humanize it to 'just now' when you're doing a messaging on notifications list.

To achieve this I propose to use optional parameter of enum type that will be 'Generic' by default and will return everything as it is right now. But if you pass another value from this enum let's say 'FromNow' it will return 'just now'

**Comment by MisinformedDNA** [comment]
What API call are you referring to? There's lots of timespan options.

**Comment by MehdiK** [comment]
This slipped under my radar. I'm not so sure about the suggestion tbh. Can you provide a code sample please?

**Comment by ilanosortap** [comment]
hey i am a beginner, can i work on this task, if yes then can you tell me what exactly needs to be done?

**Comment by MehdiK** [comment]
Closing this issue as it's been sitting here stale for quite a while.
