### ISSUE TITLE
Ordinalize not working in PT, only for PT-BR

### ISSUE THREAD

**Issue by tlfbrito** [Humanizr/Humanizer#415]
I'm trying to use the Ordinalize to transform 1 into 1st with 
`1.Ordinalize()` but the result was 1 again.

Do I need to to a special configuration?
I also have tried other example: `"men".ToQuantity(2) => "2 men"` and it worked...

**Comment by tiagobrito** [comment]
This is related to https://github.com/MehdiK/Humanizer/pull/416 because my culture is defined as pt and not pt-br.
I've created a PR to fix this issue.

**Comment by tiagobrito** [comment]
@MehdiK Is there a way to register new Ordinalizers from custom classes? If yes, can you post an example?
Thanks in advance!

**Comment by MehdiK** [comment]
@tiagobrito thanks for reporting the error and submitting the PR.

> Is there a way to register new Ordinalizers from custom classes? If yes, can you post an example?

You should be able to do it by `Configurator.Ordinalizers.Register("pt", new PortugueseOrdinalizer())`.

**Comment by tiagobrito** [comment]
If you need more work in PT/PT-BR let me know

**Comment by onovotny** [comment]
Was the corresponding PR merged? Is this still an open issue?

**Comment by SimonCropp** [comment]
Closing due to no response
