### ISSUE TITLE
Cross platform build

### ISSUE THREAD

**Issue by krippz** [Humanizr/Humanizer#422]
Hi, I was wondering if there is any interest in having Humanizer build cross platform. I'm happy to contribute :)

Personally I work on OS X, Linux and Windows. I have a simple implementation of cross platform build using [FAKE](https://github.com/fsharp/FAKE) (fsharp make).

**Comment by hazzik** [comment]
The Humanizer is already PCL with target of many platforms, including Xamarin iOS and Android. The package is built by CI. So what is the exact problem?

**Comment by krippz** [comment]
We'll not so much a problem but inconvenience when working on a different platform. What I mean is that when I'm working in OS X it would be nice to build, run test and all of that niceness when developing. 

Not have to switch to a different os to compile, or push a change that is not tested. Shortens the feedback loop when developing on a cross platform setup.

I've setup a very basic implementation to be able to build and run test locally on my OS X machine.

**Comment by hazzik** [comment]
But what's the problem with xbuild?

**Comment by krippz** [comment]
Again it's not a problem, xbuild and msbuild work. What I was suggesting was to make the workflow simpler, editing .proj files, edit msbuild/xbuild xml build targets is kinda hard and confusing.

**Comment by MehdiK** [comment]
I'm a Mac user and I'd love to see a simple Mac working environment for
Humanizer. I think we're very close but not quite there yet.

I'd love to see a simple solution. Would you be able to send a PR? I can
verify it on my machine and maybe I'll eventually be rid of the windows VM
and need for VS license!! :)

**Comment by hazzik** [comment]
>and need for VS license!!

It's free:)))

**Comment by MehdiK** [comment]
Yeah, you're right. I just want to use atom on osx tbh.
