### ISSUE TITLE
Ordinal suffixes as part of a sentence in Humanize() method

### ISSUE THREAD

**Issue by dirkrombauts** [Humanizr/Humanizer#463]
Hi,

When I call

```
"ThisIsThe4thWikiWord".Humanize(LetterCasing.Title);
```

I hope to get as result

```
This Is The 4th Wiki Word
```

Instead I'm getting

```
This Is The 4 Th Wiki Word
```

Am I doing something wrong? Or is this functionality not (yet) in Humanizer?

**Comment by VladimirMakaev** [comment]
I have the same issue with "O2" want to have it together after Humanize instead I get "O 2"

**Comment by MehdiK** [comment]
Hi @dirkrombauts and @VladimirMakaev. That's the expected outcome. Humanizer doesn't currently take ordinals into account. Happy for your to submit a PR.

**Comment by dirkrombauts** [comment]
Hi @mehdik I appreciate that an open source project lives by the pull requests from other people (I'm maintaining a project myself). I have to be honest and say that I won't be able to send you a PR in the future. I'm sorry, I wish things were different.

**Comment by onovotny** [comment]
What should the grammar/rules be for this? Like in the case of O2 vs 4th? 

Should it assume that lower-case letters following a number should be part of the number?
How about O2? Number following upper-case letter? 

So o2 would still be `O 2`

**Comment by dirkrombauts** [comment]
I would expect that whenever numbers are followed by st, nd, rd, and th, these suffixes remain with the numbers:

- `The501stLegion`  => `The 501st Legion`
- `2ndPlace` => `2nd Place`
- `The3rdMan` => `The 3rd Man`
- `ThisIsThe4thWikiWord` => `This Is The 4th Wiki Word`

As for numbers following letters, maybe @VladimirMakaev can give his take on that.

**Comment by onovotny** [comment]
I'm not sure that it's necessary to look for specific suffixes, that might be too restrictive too.

For example: `IWant2kFrobs` -> `I Want 2k Frobs`. The suffixes would be language specific too, which adds to the complexity of parsing. If lower-case letters following a number would remain attached, I think that would work?

**Comment by dirkrombauts** [comment]
You're probably right, I'm overthinking it. The suffixes are indeed language-specific, for example German uses a dot `.` for all numbers: 1., 2., 3., 4., ...

**Comment by onovotny** [comment]
I will express my total ignorance of German grammar/numbering, but how does the dot play in and how should it be treated in this case (if different from what it currently does?)

**Comment by dirkrombauts** [comment]
Put in the simplest terms that I can think of (mind you, German isn't my native tongue so maybe a German speaker can explain this better): English uses suffixes for numbering, and German replaces all those suffixes with a dot. So for example:

- `The 501st Legion` is (in German) `Das 501. Legion`
- `2nd Place` is `2. Platz`
- `The 3rd Man` is `Der 3. Mann`
- `This Is The 4th Wiki Word` is `Das Ist Das 4. Wiki Wort`
- It works the same for dates: *Back To The Future Day* is `October 21st 2015` in (American) English, and `21. Oktober 2015` in German.

**Comment by dirkrombauts** [comment]
Thanks! Do you have an estimate when you will be able to release a new nuget package?

**Comment by onovotny** [comment]
They should already be up on the MyGet feed. I'm waiting on MyGet to release a fix to their site around publishing packages with satellites before I can publish to NuGet.org. That might be another couple of weeks.
