### ISSUE TITLE
How-Do_I_HumanizeSomething_LikeThis-String

### ISSUE THREAD

**Issue by DotNetRockStar** [Humanizr/Humanizer#480]
How do you go about humanizing something that may have many different things like underscores, dashes, camel casing, etc...?

string humanized = "How-Do_I_HumanizeSomething_LikeThis-String".Humanize();
Assert.IsEqual(humanized, "How Do I Humanize Something Like This String"); // fails.

Thanks!

**Comment by onovotny** [comment]
Just curious but where is that string coming from?

**Comment by DotNetRockStar** [comment]
Algorithms that I am running against strings on www.DynamicApis.com.  Due to not being able to determine what a string is that someone may enter, I need to cover all cases.

**Comment by jfgingras** [comment]
How about looping until the string stay the same? Does that make sense? Or
does Humanize can't handle at all this string?
Le 17 nov. 2015 9:06 PM, "Jerrod Horton" <notifications@github.com> a
écrit :

**Comment by DotNetRockStar** [comment]
I did consider doing something like what I think you are talking about. I was hoping that Humanize might be able to detect and make readable. If it is not designed to do it them I can figure something else out. 

Thanks for the reply

**Comment by MehdiK** [comment]
How about Humanize().Humanize()?

The first one gets rid of _ and the second one adds space between words.

**Comment by jeremysimmons** [comment]
do you need Humanize at all for this?
"How-Do_I_HumanizeSomething_LikeThis-String".Split('-', '_').Aggregate((l,r) => l + " " + r)

**Comment by DotNetRockStar** [comment]
I was hoping to be able to use Humanizer to parse and make things readable for me without me having to write the code myself.  I don't know what special characters are going to be in between words in my situation so hard coding dashes and underscores is something I was hoping to avoid.

Thanks everyone.
