### ISSUE TITLE
"Products".IsSingular() | "Products".IsPlural()

### ISSUE THREAD

**Issue by DotNetRockStar** [Humanizr/Humanizer#481]
I cannot seem to find a way to tell me if a string is plural or singular but I do see a method to convert to singular/plural.  Is there something exposed to allow me to do this by chance?  If not, what are your thoughts on adding something like this?

var str = "products";
bool isPlural = str.IsPlural();
bool isSingular = str.IsSingular();

Assert.IsTrue(isPlural);
Assert.IsFalse(isSingular);

Thanks!

**Comment by DotNetRockStar** [comment]
Also, it would be awesome if I could do stuff like this (currently need to do this):

string str = "WhatsUpdude";
bool isCamelCased = str.IsCamelCased();
bool is

**Comment by hazzik** [comment]
Humanizer is not an NLP tool.

**Comment by DotNetRockStar** [comment]
Too bad. I figured since you are likely doing it under the cover anyways that you could make this project even more useful by exposing it.
