### ISSUE TITLE
Error loading shared test project on dev branch - MS Build issue

### ISSUE THREAD

**Issue by rdoubleui** [Humanizr/Humanizer#490]
I'm experiencing troubles when trying to load the shared tests project on the /dev branch:

`D:\Entwicklung git\Humanizer\src\Humanizer.Tests.Shared\Humanizer.Tests.Shared.shproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets
`

However I can confirm that the requested file is present in the folder mentioned. Also, how does one explain the difference in the path to the project and the actual file location (see above, note the missing `8.1`).

This is on a German machine using Windows 8.1 Pro and VS 2015 Enterprise.

**Comment by onovotny** [comment]
When you installed VS 2015, did you include the Windows 8.1 SDK's and Windows 10 SDK's? Microsoft didn't include them by default to save space :/

That's a strange error though as the shared project doesn't include those targets.

**Comment by rdoubleui** [comment]
Thanks, that was it. I installed both and then had to add them via Visual Studio Setup, test projects loading properly now.
