### ISSUE TITLE
ToQuantity does not support long quantities

### ISSUE THREAD

**Issue by pshrosbree** [Humanizr/Humanizer#503]
It would be useful if ToQuantity supported long quantities in addition to int. Something like the following would work but will not honor ShowQuantityAs.Words for large positive or negative quantity values:

``` csharp
public static string ToQuantity(this string input, long quantity, ShowQuantityAs showQuantityAs = ShowQuantityAs.Numeric, string format = null, IFormatProvider formatProvider = null)
{
    var str = quantity == 1 ? input.Singularize(false) : input.Pluralize(false);
    if (showQuantityAs == ShowQuantityAs.None)
        return str;
    if ((showQuantityAs == ShowQuantityAs.Numeric) || (quantity > int.MaxValue) || (quantity < int.MinValue))
        return string.Format(formatProvider, "{0} {1}", quantity.ToString(format, formatProvider), str);
    return string.Format("{0} {1}", ((int) quantity).ToWords(), str);
}
```

**Comment by hazzik** [comment]
:+1:

**Comment by mexx** [comment]
IMHO it's not really intuitive behavior.
Imagine
```
// int.MaxValue
"case".ToQuantity(2147483647, ShowQuantityAs.Words) =>
    "two billion one hundred and forty-seven million four hundred and eighty-three thousand six hundred and forty-seven cases"

// but int.MaxValue+1
"case".ToQuantity(2147483648, ShowQuantityAs.Words) =>
    "2147483648 cases"
```

I think, we should provide `ToWords` also for `long`.

**Comment by pshrosbree** [comment]
I agree. What I pasted is a quick fix I was using at the time. My problem was that my types are usually long, and frequently larger than int.MaxValue, so casting does work. While ShowQuantityAs.Words is not as clear as ShowQuantityAs.Numeric, I agree it should be supported. I was not suggesting my code as the implementation.

**Comment by onovotny** [comment]
Tagging as vNext unless this can be completed in the next couple of weeks.

**Comment by hazzik** [comment]
@onovotny I don't think that we can fix this in a couple of weeks. To make it feature complete we need to complete a lot of languages.

**Comment by onovotny** [comment]
Merged in https://github.com/Humanizr/Humanizer/commit/e88b07ee6a31aa7a0ed1f59e51a1d0edc1b7865a. Additional langs can be added as they're available.
