### ISSUE TITLE
Can't find ToMetric

### ISSUE THREAD

**Issue by KieranSmartMP** [Humanizr/Humanizer#505]
The ToMetric extension doesn't seem to exist

I have Humanizer 1.37.7 installed and the following code

double myVal = 2d;
myVal.ToMetric();

but the extension ToMetric does not seem to exist.

**Comment by aloisdg** [comment]
As far as I know, `ToMetric()` is for the next update. You should find it in the [version 2.0.0-beta0001](https://www.nuget.org/packages/Humanizer/2.0.0-beta0001). Be careful, it is a prerelease version of Humanizer.

**Comment by onovotny** [comment]
Closing out as it's in the pre-release ver. BTW, beta 2 is on NuGet now as well.
