### ISSUE TITLE
Update gh-pages docs to reflect the latest 

### ISSUE THREAD

**Issue by onovotny** [Humanizr/Humanizer#506]
The gh-pages branch needs to be updated. Not sure if this is best done with a script or manually.

**Comment by mexx** [comment]
As far as I can see the page is generated through the `GitHub Pages` generator, and as far as I know updates to this have to be done manually.

I've seen other projects doing generation and publishing as part of the release script.

One other point:
Currently the documentation only reflects the latest published version. Sometimes a developer needs to know at least from which version on the functionality was present. Just to mention, there is a https://readthedocs.org/ project aiming for exactly this purpose.

**Comment by onovotny** [comment]
:+1: I agree that it'd be nice to have specific versioned docs if someone has time to set that all up. I didn't want to hold up the 2.0 release for that though. 

BTW, if there's any outstanding issues/bugs/PR's that should go into 2.0, lets add them to #501 and mark them as the 2.0 milestone. 

The biggest thing I was hoping for was end-user testing of the new package structure to make sure nothing broke.

**Comment by MehdiK** [comment]
Happy New Year folks!

I published to the doc/pages website manually. I agree that a separate versioned api doc might be nice; that said I have not seen a single request or question over the past few years indicating any confusion around when something became available. The biggest confusion comes from the readme on GitHub being out of sync with what's on NuGet and humanizr.net; but that's rather unavoidable as the readme.md represents the LATEST while the doc website represents what's published to NuGet.

In other projects I maintained I was responsible for documentation and the docos were rather useless! In Humanizer I [pushed that back on contributors](https://github.com/Humanizr/Humanizer/blob/dev/CONTRIBUTING.md) which means readme gets updated as soon as a PR is merged in. I'm not saying this is the way it should stay; but this path has been quite easy to maintain!

**Comment by onovotny** [comment]
Okay folks, the docs are really the last major issue left holding up shipping 2.0. 

Question is this: should we ship 2.0 anyway and "eventually" get to the docs on humanizr.net, or does someone have an hour or so to update the gh-pages branch? I believe all the docs are present and up-to-date in the dev branch readme.md, we just need it to be translated to the website template/formatting.

**Comment by mexx** [comment]
You can simply put the content of the readme into the GH-Pages wizard in
the project settings.

**Comment by onovotny** [comment]
Nifty, did not know that!

**Comment by onovotny** [comment]
Updated!
