### ISSUE TITLE
Humanizer not taking into account es-ES locale for certain features

### ISSUE THREAD

**Issue by fferegrino** [Humanizr/Humanizer#513]
I ran into this issue while doing some work with Humanizer.Core and the localisation package Humanizer.Core.es:

For features like Ordinalisation and Pluralisation Humanizer works prefect and takes the locale strings for the language, but for others (such as DateTime & TimeSpan humanisation) it ignores the locale and outputs the result in english. i.e. Outputting `One month from now` instead of `En un mes`.

After a quick look at the code I can see that there are tests written for spanish language, though I'm not so sure of what can be wrong. 

This is the code I'm working on https://github.com/ThatCSharpGuy/humanize-post/tree/332eb1db6924370db9d1d4f2a9634d73a2a2fd8d 

I forked the repo to figure out what can be wrong, but it would be great if anyone could shed some light over this issue (or even if it really is an issue)

**Comment by onovotny** [comment]
What version of VS are you using and what version of NuGet? In your bin\debug directory, do you see an es directory?

**Comment by fferegrino** [comment]
VS Ultimate 2013, .NET 4.5, Humanizer 2.0.0-beta02-0092

And as for that folder: No, there is no folder.

**Comment by onovotny** [comment]
I just opened your solution in VS 2013, built it and I see the es folder in the bin\debug directory.

I have VS 2013 Update 5 with NuGet 2.8.60723.765 (version from the Extensions and Updates dialog).

What versions do you have?

**Comment by fferegrino** [comment]
I have the same NuGet version as you, as well the Update 5 for VS. 
Thanks for checking the solution I provided. 

I tried on two PC, I'll test later in OSX to see if the folder is generated.

**Comment by onovotny** [comment]
One thing to try too -- can you delete the `\packages` folder and then rebuild? VS should restore the packages cleanly again.

**Comment by onovotny** [comment]
Any updates on this, did that work, can this issue be closed?

**Comment by fferegrino** [comment]
Sorry for been away.

Tired on three different computers, two different projects and still no `\es` folder. Even removing the `\packages`. Do you think this could be a configuration issue on my machines?

**Comment by fferegrino** [comment]
If I manually copy the `\es` folder from `\lib\portable...` to my `bin\debug` it works as expected.

**Comment by onovotny** [comment]
I would suggest opening an issue at the NuGet repo: https://github.com/NuGet/Home/issues

**Comment by SimonCropp** [comment]
@fferegrino sorry for the delayed response. it it not possible to look further into this without a minimal repro, or better yet a PR with a test that illustrates the problem
