### ISSUE TITLE
Humanizer 2.0 framework target

### ISSUE THREAD

**Issue by JobaDiniz** [Humanizr/Humanizer#514]
Is there a way to make this package target .net 4.0?

**Comment by onovotny** [comment]
The meta package actually doesn't have any specific targets; it has a blank files element. The dependencies determine that and that'd be Core. Humanizer currently supports .NET 4.5+ (It's a PCL 259).

**Comment by JobaDiniz** [comment]
Sorry, I edited my question seconds after I've posted it..

**Comment by onovotny** [comment]
Is this still an issue then or can I close this?

**Comment by hazzik** [comment]
@onovotny, close it. The support of .NET 4-4.51 has ended a week ago (12/1/16)
