### ISSUE TITLE
Question: Does humanizer support partial datetimes?

### ISSUE THREAD

**Issue by Bartmax** [Humanizr/Humanizer#515]
If I have a partial date.
for example, only the year, or the year and month (no day)

does humanizer have built in methods to construct smart string based on that or I should use my own logic?

**Comment by aloisdg** [comment]
If Humanizer doesnt support it and you build it, feel free to open a Pull Request for it. :tada:

**Comment by SimonCropp** [comment]
@Bartmax no it doesnt
