### ISSUE TITLE
Number to number extensions

### ISSUE THREAD

**Issue by i3arnon** [Humanizr/Humanizer#518]
I think it would be nice to add to the convenient extensions for `TimeSpan`, `ByteSize` extensions that simplify writing big numbers, for example:

    int size = 20.Millions();

Instead of:

    int size = 20000000;

It's clearer to read, simpler to write and reduces the chance for errors.

I plan on using this extensively in my configuration defaults (e.g. `BounedCapacity = 10.Millions()`, `MaxDegreeOfParallelism = 1.Thousands()`)

**Comment by aloisdg** [comment]
In another hand, you could use

    int size = "20M".FromMetric(); // 20 millions

or

    int size = "20k".FromMetric(); // 20 thousands

I will works as expected.

**Comment by aloisdg** [comment]
And if you really want to use words:

```c#
private static T UseMetric<T>(this T input, string unit)
{
    return (input + unit).FromMetric();
}

public static long Millions(this long input)
{
    return input.UseMetric<long>("M");
}
```

**Comment by mexx** [comment]
From the performance point of view the proposed implementation in #519 is pretty good, as it only uses simple multiplication with a constant. Further the proposal provides implementations for the common numeric types, where `FromMetric` only returns `double`.

**Comment by aloisdg** [comment]
> From the performance point of view the proposed implementation in #519 is pretty good

I know. This is why I added "My only concern for both is performance." at the end of my post. "Both" are `UseMetric` and `MultiplyByTen`.

> `FromMetric` only returns `double`

I can change that if you think it is worth it.

Sorry If my comments were mistaken. I just share some alternatives. I think #519  is a good idea. The implementation, is simple, stupid and works very well. :+1:

**Comment by mexx** [comment]
> I can change that if you think it is worth it.
I wonder how you would achieve this, as the method can't be overloaded only by changing the result type.

You don't have to be sorry, to be able to discuss on alternatives is always good :+1:. It drives learning other approaches to the problem and an alternative can be a good fit in some other scenario for anyone reading this discussion someday.
