### ISSUE TITLE
Extension methods conflicting with 'fluent assertions' project

### ISSUE THREAD

**Issue by fedjabosnic** [Humanizr/Humanizer#524]
There seems to be a conflict for a number of your extension methods with ones from the **Fluent Assertions library** (https://github.com/dennisdoomen/fluentassertions).

For example:
- FluentAssertions.TimeSpanConversionExtensions.*
- Humanizer.NumberToTimeSpanExtensions.*

Both extension methods are in **root namespaces**, so the only solution seems to be to call the extension methods as static methods but that kind of defeats the purpose of both libraries. I suggested they may be able to move their extensions to a lower level namespace (as it is more of a utility extension for them than core functionality) but perhaps you guys can collaborate on a smarter solution. 

Being able to use both libraries together would be ideal

Related issue: https://github.com/dennisdoomen/fluentassertions/issues/352

**Comment by ilanosortap** [comment]
I would like to work on this issue, though i ll need some help

**Comment by MehdiK** [comment]
Quoting the discussion from FluentAssertion library: "_This would be not just a breaking change but a huge one and completely unnecessary. Just call as a static method._" and I completely agree. Closing this issue.
