### ISSUE TITLE
Humanizer causing failed Visual Studio Team Services Automated Builds

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Humanizr/Humanizer#527]
My builds for my UWP app won't compile on Visual Studio Team Services. I get the following issues:

Humanizer.Core.da 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.bn-BD 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.cs 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.es 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.af 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.el 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.fa 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.ar 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.de 2.0.0 is not compatible with UAP,Version=v10.0.
Humanizer.Core.bg 2.0.0 is not compatible with UAP,Version=v10.0.

Any idea how to correct this? I am only interested in en / en-US strings.

**Comment by onovotny** [comment]
What version of VS Team Services is there? Is this the vNext agent or Team Build?

There were some NuGet bugs fixed in NuGet 3.3 around this so you need to make sure you're using at least that version to do the nuget.exe restore on the sln.

**Comment by onovotny** [comment]
If you only want English anyway, you can also just install Humanizer.Core instead of Humanizer.

**Comment by AmitBhatnagar24** [comment]
Confirmed that installing just the Core lib allows the build to complete.
