### ISSUE TITLE
Installing NuGet package Humanizer.2.0.1. Errors after installation 

### ISSUE THREAD

**Issue by ZeoxZeos** [Humanizr/Humanizer#528]
Hi Team,
After installing packages **(Install-Package Humanizer
Installing NuGet package Humanizer.2.0.1. Successfully installed 'Humanizer 2.0.1' to )**
 I get the following errors 39 of them

Error	NU1002	The dependency Humanizer.Core.es 2.0.1 in project **** does not support framework DNX,Version=v4.5.1.	***	D:\Projects\NameOfProject\***\project.json	
Regards
Zeonn

**Comment by onovotny** [comment]
Hi @ZeoxZeos,

Right now the DNX tooling is discontinued and is moving to the dotnet CLI. As these are all changing rapidly, we are waiting for the RC2 bits with the new tooling before addressing any potential bugs in this area.

As the dotnet CLI uses NuGet 3.4, we do not anticipate issues.
