### ISSUE TITLE
Please don't install 25+ nuget packages by default

### ISSUE THREAD

**Issue by dotnetchris** [Humanizr/Humanizer#534]
I really disagree with `Install-Package Humanizer` results in 25+ nuget packages being installed. No one would ever expect that. It even took Nuget 120 seconds to install and i couldn't even cancel the installation.

**Comment by mexx** [comment]
It was done for backwards compatibility. And IMHO it's the problem of NuGet and not some package to being slow or not have an ability to cancel an ongoing operation.

If you don't want all locales you should install `Humanizer.Core` for `en` instead and the `Humanizer.Core.{locale}` for locales you are interested in.

**Comment by mexx** [comment]
Btw. it's also mentioned on the [documentation](http://humanizr.net/#specify-lang).

**Comment by onovotny** [comment]
I would add that the easiest way to not see or deal with all of the child packages would be to use project.json. There are tons of benefits to it:
https://oren.codes/2016/02/08/project-json-all-the-things/

**Comment by Spiralis** [comment]
Even when installing Humanizer.Core alone, 15 (!) additional dependencies are installed:
- System.Linq
- System.Reflection.Extensions
- System.Reflection.Primitives
- System.Resources.ResourceManager
- System.Runtime
- System.Collections
- System.Diagnostics.Debug
- System.Globalization
- System.Runtime.Extensions
- System.Text.Encoding
- System.Threading.Tasks
 -System.IO 
- System.Reflection 
- System.Threading
- System.Text.RegularExpressions

These are all (mostly I think) assemblies that my WPF application already has access to as a part of the .Net framework. @onovotny, why are they needed?

**Comment by onovotny** [comment]
Hi @Spiralis, this is part of `dotnet` and  `.NET Standard`, where packages have to define their dependencies. `packages.config` is old and slow; my suggestions, if possible, would be to follow my blog post (above) for how to convert your project/solution to use `project.json` for packages. `project.json` can be used with any project type and is much easier.

**Comment by dotnetchris** [comment]
Address by updating readme https://github.com/Humanizr/Humanizer/pull/561

**Comment by anjdreas** [comment]
@onovotny Converting from `packages.config` to `project.json` is not a trivial undertaking for ASP.NET apps, that out of the box rely on a big set of nugets. Several of them, like jquery, have content files that are not compatible with `project.json` AFAIK.

I believe it is recommended that nuget libs cater for both `packages.config` and `project.json` scenarios, by defining dependencies for both `dotnet` and older style .NET frameworks like `net45`.

I have a .NET 4.5.2 ASP.NET app, and when I add the `Humanizer.Core` nuget, I get all these 15 nugets that are already part of my .NET framework and have no place in my `packages.config` of `.csproj`. 

Proprosed solution: Add a `net45` dependency section with empty dependency list. Or possibly `net40` or `net35` instead, if those cover .NET 4.5.2 as well.
