### ISSUE TITLE
Keep assembly information/version up-to-date.

### ISSUE THREAD

**Issue by cristianst85** [Humanizr/Humanizer#535]
Assembly version number is still 1.0. Is there a reason for this?

**Comment by hazzik** [comment]
I think it should be 2.0. But changing it in the bugfix will be a breaking change, wont' it?

**Comment by cristianst85** [comment]
Why not for each release?

**Comment by onovotny** [comment]
I just double-checked the CI feeds and the assembly version matches the nuget ver
