### ISSUE TITLE
Error: You must add a reference to assembly 'System.Runtime'

### ISSUE THREAD

**Issue by prad9** [Humanizr/Humanizer#537]
HI

I'm getting following errors after upgrading to 2.x from 1.37.x. My MVC project doesnt even compile? 

Error	11	The type 'System.IComparable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Error	12	The type 'System.IFormattable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	
Error	10	The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	
Error	13	The type 'System.ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	

Is there any alternative? Or should i revert back my change to v1.37.x

**Comment by onovotny** [comment]
What is the .NET and VS version of your MVC project?

**Comment by prad9** [comment]
Sorry i think that's what the case is. .Net 4.5 and MVC 4. It is working now after reverting to old version.

**Comment by onovotny** [comment]
Humanizer is a regular PCL 259, it should work there.

**Comment by onovotny** [comment]
What version of VS are you using? Do you have any instances of `ImplicitlyExpandDesignTimeFacades` in your csproj file?

**Comment by onovotny** [comment]
@prad9 Please try @davkean's suggestion here: https://github.com/Humanizr/Humanizer/issues/533#issuecomment-197407376 and see if that works for you.

**Comment by onovotny** [comment]
I've updated the documentation to reflect the need for this here:
https://github.com/Humanizr/Humanizer#aspnet4mvc

**Comment by wldevries** [comment]
I had this same problem in an XNA game I manually updated to .NET 4.5 by editing the csproj file. To fix this I had to include a .net target file at the top of the .csproj file.

    <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />

**Comment by wldevries** [comment]
I had the same problem with an XNA project that I manually upgraded to .NET  4.5. To fix it I had to manually include all the references in the .csproj file as follows:

    <Reference Include="System.Runtime"/>
    <Reference Include="System.Globalization"/>

When inspecting the references in the project view you can see they actually point to `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades`. I don't want relative file references to program files and not including a hintpath seems to work fine.

**Comment by dotnetchris** [comment]
@wldevries thanks for your comment, this helped me on an entirely unrelated issue to Humanizer but that that ulimately adding those references by hand in the csproj was what i needed to do.

One slight recommendation i would make, is you likely want 

```xml
	<Reference Include="System.Runtime">
		<Private>True</Private>
	</Reference>
```
Otherwise if you use the deploy capabilities of visual studio, it will likely pretend that file doesn't exist and not include in it in the deploy bin folder.

**Comment by wldevries** [comment]
The solution _works_, but it's not the way it should be solved. You should add a reference to a facade  `System.Runtime` library. For .NET 4.5.2 this would be `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades`

https://support.microsoft.com/en-us/help/2971005/error-message-when-you-compile-applications-to-target-the-net-framewor
