### ISSUE TITLE
Add "avant-hier" and "après-demain" to french

### ISSUE THREAD

**Issue by aloisdg** [Humanizr/Humanizer#543]
Hello,

There is no support for this two french expressions. It could be nice to implement them.

You can find more informations on [WordReference](http://www.wordreference.com/fren/avant-hier).

I may implement it myself next month. If you want to do it before, go for it! ;)

**Comment by aloisdg** [comment]
In `src/Humanizer.Tests.Shared/Localisation/fr/DateHumanizeTests.cs`:

```C#
[Theory]
[InlineData(1, "hier")]
[InlineData(2, "avant-hier")] // new
[InlineData(10, "il y a 10 jours")]
public void DaysAgo(int days, string expected)
{
        DateHumanize.Verify(expected, days, TimeUnit.Day, Tense.Past);
}

[Theory]
[InlineData(1, "demain")]
[InlineData(2, "après-demain")] // new
[InlineData(10, "dans 10 jours")]
public void DaysFromNow(int days, string expected)
{
        DateHumanize.Verify(expected, days, TimeUnit.Day, Tense.Future);
}
```

To allow this we have to change it in the Resx file `/src/Humanizer/Properties/Resources.fr.resx` :

```xml
<data name="DateHumanize_SingleDayAgo" xml:space="preserve">
    <value>hier</value>
</data>

<data name="DateHumanize_SecondDayAgo" xml:space="preserve">
    <value>avant-hier</value>
</data>

<data name="DateHumanize_SingleDayFromNow" xml:space="preserve">
    <value>demain</value>
</data>

<data name="DateHumanize_SecondDayFromNow" xml:space="preserve">
    <value>après-demain</value>
</data>
```

If we change this, I guess we are will have to change the other resx too. If something like this would fit:

````xml
<data name="DateHumanize_SecondDaysAgo" xml:space="preserve">
    <value>{0} days ago</value>
</data>

<data name="DateHumanize_SecondDaysFromNow" xml:space="preserve">
    <value>{0} days from now</value>
</data>
```

Bascially, SecondDaysFromNow is a copy of `MultipleDays`.

What do you think? @onovotny @hazzik

**Comment by hazzik** [comment]
"Two days from now" and "two days ago". Is ok for me.

**Comment by aloisdg** [comment]
@hazzik Should I implement it for v2.1?

**Comment by hazzik** [comment]
If you can implement this in next day or so, I would say yes. If no - please hold till 2.2/3.0.

**Comment by aloisdg** [comment]
Don't wait for it. I should have some times Tuesday, but I cant be sure. It is not a critical issue. It can wait.

**Comment by hazzik** [comment]
- RU (Russian)
  - Two days from now => "послезавтра"
  - Two days ago => "позавчера"
- UK (Ukrainian)
  - Two days from now => "післязавтра"
  - Two days ago => "позавчора"
- ES (Spanish)
  - Two days ago => "anteayer"
- IT (Italian)
  - Two days ago => "avantieri"
- SV (Sweden)
  - Two days from now => "övermorgon"
  - Two days ago => "förrgår" ("i förrgår")
- DE (German)
  - Two days from now => "Übermorgen"
  - Two days ago => "vorgestern"
- DA (Danish)
  - Two days ago => "i forgårs"

**Comment by hazzik** [comment]
As I understand we have some issues with netstandard 1.0, so you should
have enough time to implement this.

**Comment by hazzik** [comment]
~~As I understand we have some issues with netstandard 1.0, so you should have enough time to implement this.~~
The 2.1 was shipped, so next minor version.

**Comment by onovotny** [comment]
@hazzik @aloisdg Can this be done anytime in the next week or so?

**Comment by hazzik** [comment]
Unlikely

**Comment by MehdiK** [comment]
We should be able to address the edge case using a custom formatter for French. [Here](https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/Localisation/Formatters/SlovenianFormatter.cs#L13) is a similar example. This way we won't have to add the two keys to other resource files. @aloisdg would you be able to add this for #544 please?

**Comment by BrownCasey** [comment]
I looked into using the formatter to handle this case. Still seems the resource files must be edited. Appreciate your thoughts on #684.
