### ISSUE TITLE
Could not load type 'DateHumanizeExtensions'

### ISSUE THREAD

**Issue by Drewster727** [Humanizr/Humanizer#550]
I'm using the Humanize library on a .net project I'm working on. When debugging in windows, I don't have any problems, however, when running my project on ubuntu (via mono v4.2.3) humanizer fails with the following exception:

"Nancy.RequestExecutionException: Oh noes! ---> System.TypeLoadException: Could not load type 'DateHumanizeExtensions' from assembly '/opt/ProjectX/Release/Humanizer.dll'. at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () <0x40b7e5c0 + 0x001a5> in <filename unknown>:0 at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) <0x7fd1f4743cb0 + 0x001fb> in <filename unknown>:0 at System.Linq.Enumerable.ToList[TSource] (IEnumerable`1 source) <0x40993df0 + 0x00070> in <filename unknown>:0 at ProjectX.UI.Modules.RequestsModule.GetMovies () <0x40d9b880 + 0x0071f> in <filename unknown>:0 at ProjectX.UI.Modules.RequestsModule.<.ctor>b__0_1 (System.Object _) <0x40d9b810 + 0x0000f> in <filename unknown>:0 at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object) at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40c0cdc0 + 0x0014f> in <filename unknown>:0 --- End of inner exception stack trace --- at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x40dcbb40 + 0x002c3> in <filename unknown>:0 "

The project uses a combination of the Nancy framework and OWIN for self hosting. I've seen the lib work before, but I'm not sure what's going on. All I'm doing is calling .Humanize() on a datetime.

Any info would be helpful. Thanks!

**Comment by aloisdg** [comment]
Did you try to run DateHumanizeExtensions without nancy and owin on mono? Can you share your code with your input?

**Comment by Drewster727** [comment]
Here's an example. I'm iterating over a list of items and creating new instances of a class called RequestViewModel. Each time I new up this model, I'm calling .Humanize() on the DateTime property "RequestedDate" -- the prop is not null, it has a date. I have tried to reproduce this on windows, but not without nancy/owin, it seems to only fail via mono/linux.

```var viewModel = collection.Select(x=>
            {
                return new RequestViewModel
                {
                    ProviderId = x.ProviderId,
                    Type = x.Type,
                    Status = x.Status,
                    RequestedDate = x.RequestedDate.Humanize(),
                    Approved = x.Available || x.Approved,
                    Title = x.Title,
                    Overview = x.Overview,
                    Available = x.Available,
                    Admin = isAdmin,
                };
            }).ToList();```

**Comment by SimonCropp** [comment]
this looks like a mismatch of assembly versions. if you still have the issue can you share a stand alone repro.

closing for now
