### ISSUE TITLE
CollectionHumanizeExtensions.Humanize causes NullReferenceException for null items

### ISSUE THREAD

**Issue by jnm2** [Humanizr/Humanizer#555]
This is a headache for me. `.Select(_ => _?.ToString() ?? string.Empty).Humanize()` seems unnecessary; wouldn't it be a sensible default to allow `.Humanize()` directly on collections containing nulls?

Happy to do a PR if you think so.

**Comment by onovotny** [comment]
Happy to accept a PR to fix this. I would think that there should be a default null value that's overridable if desired. Some people may want `String.Empty`, but others may want something like `Missing` or `<empty>`.

**Comment by jnm2** [comment]
Now that I think about it, users might expect `enumerable.Humanize()` to skip null entries entirely. It isn't very human to display `A, , , B, and C`. I'd expect each item to be trimmed and null-or-empty items to be skipped so as to avoid the comma. What do you think?

**Comment by aloisdg** [comment]
@jnm2 I agree with your behavior as default if we use a flag to allow something else. An enum like [`StringSplitOptions`](https://msdn.microsoft.com/en-us/library/system.stringsplitoptions(v=vs.110).aspx) can to the trick:

| Member name        | Description                                                                   |
|--------------------|-------------------------------------------------------------------------------|
| None               | The return value includes array elements that contain an empty string         |
| RemoveEmptyEntries | The return value does not include array elements that contain an empty string |

**Comment by jnm2** [comment]
What about this:

```c#
[Flags] enum StringJoinOptions
{
    None = 0,
    TrimEntries = 1 << 0,
    RemoveBlankEntries = 1 << 1,
    Default = TrimEntries | RemoveBlankEntries 
}
```

**Comment by jnm2** [comment]
@onovotny Need some direction- how configurable should this be? Don't want to go overboard.

**Comment by onovotny** [comment]
The options you have there seem ok -- I agree there's no need to go overboard, we can always add more later if we need.

**Comment by jnm2** [comment]
Specifically you're okay with an optional StringJoinOptions as defined [here](https://github.com/Humanizr/Humanizer/issues/555#issuecomment-223036612) with a default value that would trim all items and remove empty ones? What would the new default mean for back-compat and versioning?

**Comment by jnm2** [comment]
Wow, looks like using the # sign in commit messages doesn't go well with force-pushing to a fork. Sorry.
