### ISSUE TITLE
When using in Xamarin (and/or Forms), can't embed/bundle assemblies into native code

### ISSUE THREAD

**Issue by michaeldimoudis** [Humanizr/Humanizer#556]
Hi, so this has been causing me grief for a long time, I could not for the life of me "embed/bundle assemblies into native code" for my Xamarin Forms Android app. I finally tracked the issue down to this Humanizer library. Removing Humanizer immediately worked.

Here is the error:
`[aot-compiler stdout] JIT time: 26 ms, Generation time: 116 ms, Assembly+Link time: 68 ms.[mkbundle stderr] ERROR: Duplicate assembly name 'Humanizer.resources.dll'. Both 'C:\Workspace\my-fancy-app\packages\Humanizer.Core.2.0.1\lib\dotnet\ar\Humanizer.resources.dll' and 'C:\Workspace\my-fancy-app\packages\Humanizer.Core.2.0.1\lib\dotnet\af\Humanizer.resources.dll' use same assembly name.`

Please note that even though the error is for AOT compilation, Humanizer is still the cause. I tried with the only option selected been "embed/bundle assemblies into native code" and I still could not get it to work at all.

Obviously to fix this might be a big breaking change, but not sure if there is an option or prebuild script to strip out all the localization DLL's or just keep English?

Thanks

Michael

**Comment by onovotny** [comment]
This is a bug with the Xamarin linker. Can you please open a Bugzilla with a repro and post the Bugzilla link here? They should be able to handle duplicate assembly names that are in different folders.

**Comment by jonpryor** [comment]
This isn't a bug with the Xamarin.Android linker. [This is a bug with `mkbundle` not supporting satellite assemblies](https://bugzilla.xamarin.com/show_bug.cgi?id=11430). Unfortunately, Humanizer uses satellite assemblies, presumably for language translations, thus triggering this limitation in "Bundle assemblies into Native Code" support.

AOT is another matter entirely, and does allow building the known repro without error.

**Comment by onovotny** [comment]
@jonpryor thanks for the clarification here. Question is, when is `mkbundle` going to be fixed The Bugzilla is over three years old.

**Comment by michaeldimoudis** [comment]
Ok I’m not sure how crazy this is, but I got it working.

Am only successfully on the Mac so far. In my Droid project I have these enabled:
- Embed assemblies in native code
- Enable ProGuard
- Enable Multi-Dex
- (also tried with and without Enable AOT & Enable LLVM Optimizing Compiler)

Now here is where the magic happens.

1. In Xamarin Studio rebuild the Droid solution in Release mode.
2. When done run this command in the terminal: `msbuild MyFancyApp.Droid.csproj /t:SignAndroidPackage /p:Configuration=Release`
3. Now go back to Xamarin Studio and “Archive for Publishing”. That command now archives the app successfully without any errors.

If I did not run the above command in terminal, archiving always fails. I can now sign and distribute the app. I’ve unzipped the APK and yes the assemblies are embedded. Have also installed the signed APK on my Android device.

Is this even possible with the `mkbundle` bug? One thing I did do, which I don’t know if it made a difference, is update the Android NDK to version r11c.

**Comment by jonpryor** [comment]
>  I’ve unzipped the APK and yes the assemblies are embedded.

That means you're not using mkbundle. The purpose of mkbundle is to *prevent* the assemblies from being embedded *as assemblies* in the `.apk`. (Instead, they're zipped and compressed into a native library. They still exist, they're just *slightly* harder to find.)

**Comment by Dids** [comment]
Any news on this? I'm seeing this on iOS (Xamarin.Forms).

**Comment by onovotny** [comment]
I would suggest raising this with Xamarin; there's not much I can do about this.
