### ISSUE TITLE
NumberToWords in French is wrong for a few numbers

### ISSUE THREAD

**Issue by ghigad** [Humanizr/Humanizer#557]
Hi,

Edit:  Added a few edge cases with thousands and millions...

In French, twenty (vingt) and one hundred (cent) have to be accorded to plural, but only when it's not followed by any other number.  Please note that in French, eighty is quatre-vingts (four times twenty...)...

Here are a few examples:

Number|Actual result|Expected value|Correct?
------|-------------|--------------|--------
80|quatre-vingt|quatre-vingts|False
81|quatre-vingt-un|quatre-vingt-un|True
400|quatre cent|quatre cents|False
401|quatre cent un|quatre cent un|True
480|quatre cent quatre-vingt|quatre cent quatre-vingts|False
80000|quatre-vingt mille|quatre-vingt mille|True
80000000|quatre-vingt millions|quatre-vingts millions|False
80080080|quatre-vingt millions quatre-vingt mille quatre-vingt|quatre-vingts millions quatre-vingt mille quatre-vingts|False
200200200|deux cent millions deux cent mille deux cent|deux cents millions deux cent mille deux cents|False
200200202|deux cent millions deux cent mille deux cent deux|deux cents millions deux cent mille deux cent deux|False

Thank you for your help.

**Comment by aloisdg** [comment]
Thank you for the input. There is already a on-going fix for this. Feel free to share your opinion on #542

**Comment by jaxx-rep** [comment]
As mentionned by @aloisdg there a fix for this included in my PR #542 

See commit 11242d9dd39fd4c6a90c2668c9de885275b27b03

**Comment by hazzik** [comment]
@jaxx-rep your implementation does not cover these cases.

**Comment by hazzik** [comment]
@aloisdg @jaxx-rep @ghigad what is expected output for "200456"?

**Comment by aloisdg** [comment]
@hazzik I would say  "deux cent mille quatre cent cinquante-six".

**Comment by hazzik** [comment]
@aloisdg https://github.com/Humanizr/Humanizer/blob/11242d9dd39fd4c6a90c2668c9de885275b27b03/src/Humanizer.Tests.Shared/Localisation/fr-BE/NumberToWordsTests.cs#L50 here is "deux cent**s** mille quatre cent cinquante-six".

**Comment by aloisdg** [comment]
@hazzik Nice :)

**Comment by hazzik** [comment]
The question is what version is correct. Do I understand correctly that "deux cent_ mille" but "deux cent**s** millions"?

**Comment by hazzik** [comment]
@aloisdg 

The question is what version is correct.

"deux cent**s** mille quatre cent cinquante-six"
OR
"deux cent_ mille quatre cent cinquante-six"

 Do I understand correctly that it should be "deux cent_ mille" but "deux cents millions"?

**Comment by aloisdg** [comment]
@hazzik I think it is "deux cent mille" and "deux cent millions". There is a "s" after "cent", if there is nothing after like "deux cents" or "neuf cents".

**Comment by hazzik** [comment]
@aloisdg [wiki](https://fr.wikipedia.org/wiki/Nombres_en_fran%C3%A7ais) says following:


- 300 000 = trois-cent-mille
- 300 000 000 = trois-cents millions

**Comment by aloisdg** [comment]
Indeed. So it is "deux cents millions". I am not sure for the "-". [francaisfacile.com](http://www.francaisfacile.com) doesnt use it.

**Comment by ghigad** [comment]
The rule for "vingt" and "cent" is that they take an "s" when they are last:  quatre-vingts, trois cents, but they don't take an "s" when another number follows:  "quatre-vingt-trois", "trois cent vingt-quatre".  "Mille" is always invariable (never takes an "s").

The rule for the "-" is that numbers under 100 take a "-" (83 -> "quatre-vingt-trois"), but numbers above one hundred don't take "-" (2000 -> "deux mille").  So, 1234 becomes "mille deux cent trente-quatre":  "mille deux cent" is above 100 and "trente-quatre" is under 100.

Millions and above are considered as nouns.  So we always accord them, no matter what follows:  "deux millions quatre cent mille".  Note that "millions" is accorded and "cent" is not.

I hope this clarifies things a bit...

**Comment by aloisdg** [comment]
@ghigad The [french spelling reforms of 1990](https://en.wiktionary.org/wiki/Appendix:French_spelling_reforms_of_1990#Numbers) disagrees. @hazzik is right by following wikipedia.

Traditional spelling
cent vingt-et-un
trois cent trente-deux mille cinq cent un

Reformed spelling
cent-vingt-et-un
trois-cent-trente-deux-mille-cinq-cent-un

**Comment by aloisdg** [comment]
@hazzik I tried your code on my computer. Everything looks god so far.

**Comment by hazzik** [comment]
@aloisdg there was explanation on the original implementation why we stick with the pre 1990 orthography

**Comment by aloisdg** [comment]
@hazzik Ok. It could be nice to add this somewhere (docs, comments, etc.)
