### ISSUE TITLE
de-DE `ToQuantity` Support

### ISSUE THREAD

**Issue by Camuvingian** [Humanizr/Humanizer#560]
In LinqPAD, I do the following 

```
void Main()
{
    //Thread.CurrentThread.CurrentCulture = new CultureInfo("en");
    Thread.CurrentThread.CurrentUICulture = new CultureInfo("en");
    string s = "case".ToQuantity(5, ShowQuantityAs.None);
    s.Dump();
    1.ToWords(GrammaticalGender.Masculine).Dump();

    //Thread.CurrentThread.CurrentCulture = new CultureInfo("de-DE");
    Thread.CurrentThread.CurrentUICulture = new CultureInfo("de-DE");
    s = "der Mann".ToQuantity(2, ShowQuantityAs.None);
    s.Dump();
    1.ToWords(GrammaticalGender.Masculine).Dump();
}
```

which outputs:

> cases
> one
> der Manns
> eins

This is right apart from the pluralization of "der Mann", which should be "die Männer" (or something similar. I don;t speak German but I know appending an "s" in this case is not correct. Is there full support for German in this case or am I not using the code correctly? 

Thanks for your time.

**Comment by mexx** [comment]
Currently there is no build in support for other languages then English for `Pluralize` or `Singularize`, which are used internally by `ToQuantity`.
However you could feed the used `Vocabulary` with the rules you require, something like `Humanizer.Inflections.Vocabularies.Default.AddIrregular("Mann", "Männer")`.
Please note that all rules will be applied to the input in any language.

**Comment by hazzik** [comment]
I think we need to move English-only extensions into a separate namespace.

**Comment by MonsterMMORPG** [comment]
ah i see. i installed this just for pluralize turkish and i see it doesnt support :(

**Comment by hazzik** [comment]
Related to #668

**Comment by MehdiK** [comment]
I see some value in moving English-only extensions to a separate namespace; but I'm torn on it. My main concern is that what's English-only today could be extended to other languages in the future, like how everything started in Humanizer, and each namespace change is a breaking change. I think at some point we discussed introducing localisation for `Pluralize` and `Singularize` and don't quite remember the outcome of that TBH; but I don't see why that couldn't work.

**Comment by MehdiK** [comment]
Found it. It's discussed at #197. Closing this issue now.
