### ISSUE TITLE
"callback".Singularize() returns null

### ISSUE THREAD

**Issue by gerektoolhy** [Humanizr/Humanizer#562]
`"callback".Singularize()` returns `null`.

I expect this to return "callback".

**Comment by hangy** [comment]
`"callback".Singularize(false)` returns `"callback"`.

The optional parameter `inputIsKnownToBePlural` defaults to `true`, so it expects "callback" to be a plural. If you're not sure if the input is a plural, then pass `false` to return the original word, if none of the plural rules apply.

**Comment by dariusdamalakas** [comment]
@hangy , yup, thats what i've done. Still, returning null is what I would never expect calling on a non-null string.

**Comment by Ashera138** [comment]
Should this issue be closed? It looks like the [`Singularize()`](https://github.com/Humanizr/Humanizer/blob/master/src/Humanizer/Inflections/Vocabulary.cs#L118) method was updated at some point to address this. 

However, as a side note, this was not updated in the [`Pluralize()`](https://github.com/Humanizr/Humanizer/blob/master/src/Humanizer/Inflections/Vocabulary.cs#L92) method above it.
