### ISSUE TITLE
Push MPL2 code

### ISSUE THREAD

**Issue by aloisdg** [Humanizr/Humanizer#568]
Hello,

*tl;dr* : Can I use MPL2 for my code? Can I move my passed contribution from MIT to MPL2?

I made an Esperanto NumberToWords named Numbro. Numbro's  is inspired by the english implementation of NumberToWords (MIT) from Humanizer. I licensed Numbro's code and tests under MPL2. Do you allow me to push it as MPL2 or you prefer to have only MIT code in Humanizer?

I shared MetricNumeralExtensions (code and tests) under the MIT license. Can I move it to MPL2?

In case of trouble, I will license everything under MIT. I am just asking because I like the idea behind the MPL2. Thank you 😄 

Cheers,

**Comment by onovotny** [comment]
It would be very difficult to maintain multiple different license types for a project. I'm going to have to say that we'll need to stick with MIT-licensed code for all of Humanizer.

Thanks!

**Comment by aloisdg** [comment]
Ok no problem!

**Comment by hazzik** [comment]
MPL2 is more restrictive than MIT, so, it would effectively infect the project. So, I oppose it. 
But, as you are the creator of the Numbro it shall be not a problem to re-license the parts of the code contributed here to the MIT license.

**Comment by aloisdg** [comment]
@hazzik It was my plan. :)
