### ISSUE TITLE
Titleize is removing accented characters in Core.pt 2.0.1

### ISSUE THREAD

**Issue by rubenslopes** [Humanizr/Humanizer#572]
Hi,

this happens,
 
`Console.WriteLine("rubens armôa lopes".Titleize()); //Rubens Arm A Lopes`

while the expected is,

` Console.WriteLine("rubens armôa lopes".Titleize()); //Rubens Armôa Lopes`

Thank you for create and maintain such a great library

**Comment by hazzik** [comment]
Closed as duplicate of #532.
