### ISSUE TITLE
Difference Dasherize and Hyphenate

### ISSUE THREAD

**Issue by fleed** [Humanizr/Humanizer#574]
Is there a difference between Dasherize and Hyphenate?

If not, how can I convert a string like "ThisIsMyString" to "this-is-my-string"? Should I do something like this

`"ThisIsMyString".Underscore().Hyphenate()`

?

**Comment by klaus78** [comment]
See also #42

**Comment by aloisdg** [comment]
> Is there a difference between Dasherize and Hyphenate?

From @klaus78 's issue :

> Hyphenate instead of Dasherize makes more sense.

> We cannot remove Dasherize but we could add Hyphenate method that calls Dasherize.

Also the code explains it better:

```cs
        /// <summary>
        /// Replaces underscores with dashes in the string
        /// </summary>
        /// <param name="underscoredWord"></param>
        /// <returns></returns>
        public static string Dasherize(this string underscoredWord)
        {
            return underscoredWord.Replace('_', '-');
        }
		
        /// <summary>
        /// Replaces underscores with hyphens in the string
        /// </summary>
        /// <param name="underscoredWord"></param>
        /// <returns></returns>
        public static string Hyphenate(this string underscoredWord)
        {
            return Dasherize(underscoredWord);
        }
```

[source](https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/InflectorExtensions.cs#L115)
