### ISSUE TITLE
not installable for projects that targets .NET client profile

### ISSUE THREAD

**Issue by johannes-schmitt** [Humanizr/Humanizer#575]
Humanizer.Core cannot not be installed (via NuGet) if the the project targets ".NET Framework 4 Client Profile" or ".NET Framework 3.5 Client Profile" (see attached screenshots)

![error_with_3 5_client_profile](https://cloud.githubusercontent.com/assets/9046926/17017346/4e457744-4f33-11e6-9e34-eeec7de609f7.PNG)
![error_with_4 0_client_profile](https://cloud.githubusercontent.com/assets/9046926/17017345/4e42508c-4f33-11e6-981a-fdc0a30bb19a.PNG)

**Comment by hangy** [comment]
> The earliest .NET Framework to support a .NET Platform Standard version is .NET Framework 4.5. This is because the new portable API surface area (aka System.Runtime based surface area) that is used as the foundation for the .NET Platform Standard only became available in that version of .NET Framework. Targeting .NET Framework <= 4.0 requires multi-targeting.

([Source](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#observations))

By targeting netstandard1.0, this basically makes Humanizer incompatible with .NET <= 4.0.

**Comment by onovotny** [comment]
Humanizer 2.x has been .NET 4.5+ only. For earlier versions, I would recommend using the 1.37 version.

**Comment by johannes-schmitt** [comment]
Thanks for the quick reply and thanks for the clarification.

**Comment by talynone** [comment]
Does Humanizer support .Net Core 1.0? I believe .Net core is supposed to implement the .NET standard library, but when I try to compile a project with the Humanizer Nuget package I get the following error:

"Error NU1002	The dependency Humanizer.Core.bn-BD 2.1.0 does not support framework .NETCoreApp,Version=v1.0."
