### ISSUE TITLE
.NET Core 1.0 Support?

### ISSUE THREAD

**Issue by talynone** [Humanizr/Humanizer#577]
Does Humanizer support .Net Core 1.0? I believe .Net core is supposed to implement the .NET standard library, but when I try to compile a project with the Humanizer Nuget package I get the following error:

"Error NU1002 The dependency Humanizer.Core.bn-BD 2.1.0 does not support framework .NETCoreApp,Version=v1.0."

**Comment by onovotny** [comment]
It may be related to this:
https://github.com/dotnet/cli/issues/3396

There's a bug in the CLI tools

**Comment by onovotny** [comment]
Have you tried the `Humanizer.xproj` package? I created that as a workaround for this. Please re-open if this is still an issue.
