### ISSUE TITLE
.Humanize() on "Arabic" letters returns empty string (or any other casing)

### ISSUE THREAD

**Issue by Korayem** [Humanizr/Humanizer#578]
I have an app where string being humanized could be of any culture.

I have Thread Culture properly set to Arabic.

Expected behavior: It should return exact same string.

**Comment by hazzik** [comment]
Could you please check 2.1?

**Comment by Korayem** [comment]
Ok

**Comment by Korayem** [comment]
Using Xamarin Studio 6 and getting following error while upgrading:

> Using NugetThe 'Humanizer.Core 2.1.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'.

**Comment by hazzik** [comment]
@onovotny is there any chance to back-port #564 to 2.0.x and 1.x branches?

**Comment by Korayem** [comment]
Never mind, I switched to Visual Studio to update the nugets to v2.1. It's still occurring. The values returned are empty string.

I have installed
* Humanizer.core
* Humanizer.core.ar

**Comment by onovotny** [comment]
For Xamarin Studio, you need to be on the beta channel.

**Comment by Korayem** [comment]
@onovotny kindly read my comment above. I switched to VS to update the nugets but still same problem with me

**Comment by onovotny** [comment]
We'll need more information to diagnose. What project type, what does your solution look like, what does your project look like?

**Comment by Korayem** [comment]
HYG

```
class Program
    {
        static void Main(string[] args)
        {
            var x = "هلا".Humanize();
            Console.WriteLine($"Arabic humanized: {x}");
        }
    }
```

**Comment by onovotny** [comment]
What kind of app is this? .NET 4.5 or .NET Core App 1.0?

**Comment by Korayem** [comment]
@onovotny  .net 4.6.1 command line as shown in `packages.config` above

**Comment by hangy** [comment]
These characters are of the [Unicode category "Letter, Other"](http://www.fileformat.info/info/unicode/category/Lo/list.htm) and currently not matched by [the regex](https://github.com/Humanizr/Humanizer/blob/39f3aa5cfc43524ab23302e8407c9ecf8ad23cdd/src/Humanizer/StringHumanizeExtensions.cs#L17). The easiest fix would be to pass them through as-is, but I can't say if that's enough to "humanize" Arabic, Hebrew or Egyptian hieroglyphics …
