### ISSUE TITLE
TimeSpan.Humanize does not behave as expected

### ISSUE THREAD

**Issue by aequasi** [Humanizr/Humanizer#583]
WIth the following timespan of: `296.19:32:06.8100684`

Using the following code:

```
string createdAt = timeSpan.Humanize(10,  minUnit: TimeUnit.Day, maxUnit: TimeUnit.Year);
```

I would expect the output to be: Something around 9 months, etc. But instead, it shows `2 days`

**Comment by hangy** [comment]
Apparently not implemented, yet:
https://github.com/Humanizr/Humanizer/blob/cd5bbaca80a640bf9d623b52b55d54e3e516b4a8/src/Humanizer/TimeSpanHumanizeExtensions.cs#L16
https://github.com/Humanizr/Humanizer/blob/cd5bbaca80a640bf9d623b52b55d54e3e516b4a8/src/Humanizer/TimeSpanHumanizeExtensions.cs#L113

**Comment by aequasi** [comment]
Ah, well that is disapointing

**Comment by JonPSmith** [comment]
Yes, disappointing as no warning that this would happen.

**Comment by aloisdg** [comment]
Indeed I think it should be loud too. Better, it should be implemented! 😉

@JonPSmith Could you look into it? Thank you ☺

**Comment by JonPSmith** [comment]
Hi @aloisdg,

I have participated in a few projects, but I'm on two contracts at the moment so I don't have the time at the moment.

**Comment by aloisdg** [comment]
@JonPSmith No problem!

**Comment by redwards510** [comment]
Here's a simple test case to illustrate this bug.
`var result_is_6days = TimeSpan.FromDays(370).Humanize(1, null, TimeUnit.Month, TimeUnit.Second, ", ");`

Apparently it breaks going from TimeUnit.Week to TimeUnit.Month

**Comment by hangy** [comment]
I think your PR #603 could be fine. Just check the failing unit tests. It appears that they currently validate that the cases you want to fix do not run, so it's probably just a matter of correcting the current unit tests and expanding them to check for the newly supported changes.

**Comment by reinhardtb** [comment]
Cool - thanks for the feedback - will check out those unit tests!

**Comment by akamud** [comment]
Before we start writing any code, we should see how can we convert days to months/years.  

A month has 28 days (4 weeks) or 30 days?
A year has 365 or 366 days?

Or should we use the exact value (1 month = 30.436875 days) and round it?

**Comment by onovotny** [comment]
The challenge with anything date related is that the year and locale often matter. You can use the TimeZoneInfo class to get the rules for how many days a particular year has (leap year) or however many days a month has (per month). But it's hard to do that w/o context.

Not sure the right answer here.

**Comment by JonPSmith** [comment]
I had a come up with a solution for the project I was on. I found it was really hard to do when staying in `TimeSpan` but I made it work for `DateTime`. 

I found the various answers to the stackeoverflow question [Date difference in years using C#](http://stackoverflow.com/a/4127477/1434764) useful. In the end worked out the years using [dana's answer](http://stackoverflow.com/a/4127477/1434764). 

I hope that helps.

**Comment by hazzik** [comment]
Bare TimeSpan would not make any sense without reference to a fixed point in time. E.g. 366 days is just 366 days. 

But 366 days _ago_ can be 1 year or 1 year and a day ago depending on a context.

We need to make sure that we distinguish between bare TimeSpan and TimeSpan as a difference of 2 dates & times.

For a bare TimeSpan we could implement a fuzzy logic, saying that 366 days is _about_ 1 year ago.

**Comment by akamud** [comment]
I like the idea of using fuzzy logic for bare TimeSpan

**Comment by aloisdg** [comment]
I think the fuzzy logic is good enough. It could be more precise, but I guess thats fine.
