### ISSUE TITLE
Singularize Bug; InflectorExtensions.Singularize("cookies")

### ISSUE THREAD

**Issue by DotNetRockStar** [Humanizr/Humanizer#585]
Hi there.  There are some words that seem to be coming out incorrectly and I was wondering if there is another way I can use this to get more accurate results.

```
string word = "cookies";
string humanizedWord = Humanizer.InflectorExtensions.Singularize(word);
// humanizedWord == "cooky"
```

The above code results in humanizedWord equal to "cooky" instead of "cookie".

Thanks in advance
- Jerrod

**Comment by pratikf** [comment]
I have found another instance where Singularize() acts weird. The word "Analysis" is consider singular, and **"Analysis".Singularize(false)** correctly returns **"Analysis"** back. But if it's joined with another word, it doesn't work.

For example, **"SampleAnalysis".Singularize(false)** returns **"SampleAnalysi"**, with the "s" removed in the end. What's more weird, is once I make this call, subsequently, all calls to **"Analysis".Singularize(false)** also return **"Analysi"**.
