### ISSUE TITLE
Offer way to extract acronym from string

### ISSUE THREAD

**Issue by aateeque** [Humanizr/Humanizer#591]
Wonder if there is a way in the library to extract acronyms from strings? And if there isn't, would it be something of interest? For example "Laughs out Loud" to "LOL" etc

**Comment by aloisdg** [comment]
As far as I know, there is no way to achieve this. Acronym can be tricky and opinionated.  I think the best way would be to check the input against a dictionary of well known acronyms. But we could still implement something simple as a go to solution. or use both.

**Comment by aateeque** [comment]
Yeah, guess we could do a default and provide customisation options?

**Comment by aloisdg** [comment]
@aateeque Yes why not.

**Comment by aateeque** [comment]
Cool, I'll knock something together, thanks

**Comment by SimonCropp** [comment]
Closing for age
