### ISSUE TITLE
Humanize pt-PT problem

### ISSUE THREAD

**Issue by sirfilipef** [Humanizr/Humanizer#601]
Doesn't work
`new TimeSpan(0,1,0,0).Humanize(culture: new CultureInfo("pt-PT"));`

Works
`new TimeSpan(0,1,0,0).Humanize(culture: new CultureInfo("pt-BR"));`

Any ideias?

**Comment by hangy** [comment]
So for some reason, the resource file [`Resources.pt.resx`](https://github.com/Humanizr/Humanizer/blob/b4bab9b31dfd00a70d778a03ce03f5db61ffd2e6/src/Humanizer/Properties/Resources.pt.resx) is in Portuguese, but the formatter is only registered for [Brazilian Portuguese](https://github.com/Humanizr/Humanizer/blob/a204909f36c18bfed2d9b399a5b2f55e9fe41dda/src/Humanizer/Configuration/FormatterRegistry.cs#L22). If you can confirm that the translations in `Resources.pt.resx` are correct for Portuguese in general (not just in Brazil), then the change is really easy.

**Comment by sirfilipef** [comment]
Ok I will check it out tomorrow, probably it will be the same.

**Comment by sirfilipef** [comment]
i confirm the translations in Resources.pt.resx are correct for Portuguese in general
