### ISSUE TITLE
enum with DisplayAttribute but no Description attribute fails

### ISSUE THREAD

**Issue by JonPSmith** [Humanizr/Humanizer#605]
Hi,

The following code fails on the line `MyEnums.AndThat.Humanize()`.
```C#
enum MyEnums {
	This, 
	[Display(Name = "Not Set")]
	AndThat
};
void Main()
{
	MyEnums.This.Humanize();
	MyEnums.AndThat.Humanize();
}
```
I'm not saying its urgent, but thought you should know about it.

**Comment by basildk** [comment]
The question is what we want to do in this scenario? 

- Return the value of Name (In the example "Not Set")
- Throw a more meaningfull error

**Comment by JonPSmith** [comment]
Personally I think it should return the Name, but Humaized, as that is what the code would have done if no Description attribute was present, i.e. I think the error is not handling the Attribute not being the one it expected.

**Comment by onovotny** [comment]
Will be fixed in the next release, thanks @basildk!
