### ISSUE TITLE
Porting to .NET 2.0/3.5 (Unity)

### ISSUE THREAD

**Issue by ophilbinbriscoe** [Humanizr/Humanizer#606]
Many of these transformations would be indispensable for game development. Would a particular subset of features be more or less feasible? This is something I would look at taking on myself if it's within the realm of possibility. Does the pluralization leverage the .NET pluralizing service?

Thanks for a great library!

**Comment by onovotny** [comment]
Unity is working on adding support for .NET Standard, so they'll be able to use most of the .NET ecosystem, including this library: https://github.com/dotnet/standard/blob/master/docs/faq.md#will-unity-implement-net-standard

**Comment by ophilbinbriscoe** [comment]
That is correct. However, there is no firm date on that yet - they've been talking about it for years.

**Comment by Megasware128** [comment]
While Unity is still busy I have moved on to Xenko. It feels a lot like Unity, but they do support .NET Standard and C# 6. I hope version 2.0 will use the new project system and C# 7. Might go back to Unity if they finally upgraded.

**Comment by meiblorn** [comment]
Unity now supports .NET 4.6 and C# 6 Runtime.
But when I import your lib, I get the following errors:

`Assets/Scripts/../MyScript.cs(26,101): error CS0012: The type `System.IComparable`1<Humanizer.Bytes.ByteSize>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
`Assets/Scripts/../MyScript.cs(26,101): error CS0012: The type `System.IEquatable`1<Humanizer.Bytes.ByteSize>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
`Assets/Scripts/../MyScript.cs(26,101): error CS0012: The type `System.IComparable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

What does this error mean? 

According to Rider configuration, System.Runtime is already imported.
![screen shot 2017-07-24 at 09 37 45](https://user-images.githubusercontent.com/4069585/28509493-ca1ee4d0-7053-11e7-8632-b09a3a7c1ed6.png)
![screen shot 2017-07-24 at 09 39 09](https://user-images.githubusercontent.com/4069585/28509532-0e66697e-7054-11e7-97ea-09bce54023f5.png)

Also, I've described my problem [Here: Unity forums](https://forum.unity3d.com/threads/error-you-must-add-a-reference-to-assembly-system-runtime.484773/).

Thanks!

**Comment by MehdiK** [comment]
Thanks for the discussion guys. 

@meiblorn It doesn't look like a Humanizer issue. It's complaining about `IComparable`: `The type System.IComparable' is defined in an assembly that is not referenced.`. I suspect your System.Runtime doesn't have the IComparable type! I see someone else in Unity forums has a similar problem. I'm closing this for now. Please let us know how you went with this.
