### ISSUE TITLE
Titleize Casing doesn't apply to first word within a bracket

### ISSUE THREAD

**Issue by Nikey646** [Humanizr/Humanizer#607]
If the following sentence was run through the Titleize string transformer "my summer vacation (with my family)", it would come out as "My Summer Vacation (with My Family)". Ignoring that the word "my" could start with a lower or upper case M, the "with" is not modified at all.

In some cases, the current output is as expected (EG: "Madonna (written by E. Cales in 1998)"), but in other cases the output is unexpected (My above example).

Is this the intended functionality?

**Comment by MehdiK** [comment]
No, this is a bug. Thanks for reporting.

**Comment by Nikey646** [comment]
Thanks.
