### ISSUE TITLE
add .ToMetric() rounding

### ISSUE THREAD

**Issue by tarakan12** [Humanizr/Humanizer#609]
would be great to be able to round ToMetric() result so instead of 2.663982M it would spit out 2.66M. 
it will take an optional parameter of rounding digits and potentially rounding direction

**Comment by JonCubed** [comment]
@onovotny any indication when this can be merged?

**Comment by aloisdg** [comment]
It looks nice, but the I cant try it. (Can I debug it on Linux?)

**Comment by JonCubed** [comment]
@aloisdg @onovotny I see the pr has been approved, any updates when it can be merged?

**Comment by onovotny** [comment]
@JonCubed I'm aiming to get 2.2 out in early May, thanks!

**Comment by JonCubed** [comment]
@onovotny awesome thanks looking forward to 2.2
