### ISSUE TITLE
Kebaberize?

### ISSUE THREAD

**Issue by devdigital** [Humanizr/Humanizer#611]
Is there nothing available to convert directly to kebab-case?

It seems you need to do the following:

```
var result = "MyString".Underscore().Hyphenate();
Console.Write(result);  // "my-string"
```

**Comment by aloisdg** [comment]
See [Snake Case](https://en.wikipedia.org/wiki/Snake_case) for more informations.

**Comment by onovotny** [comment]
Happy to take a PR to make this more efficient

**Comment by harpsicord86** [comment]
Has this been added to the nuget package?  Tried to use this with no success!

**Comment by onovotny** [comment]
Not yet, it will be a part of 2.2 which is going out soon. In the interim, you can always use the CI feed on MyGet as mentioned here https://github.com/Humanizr/Humanizer#install

**Comment by hazzik** [comment]
Shouldn't this be closed?
