### ISSUE TITLE
[question] speedup test case discovery

### ISSUE THREAD

**Issue by basinilya** [Humanizr/Humanizer#615]
I want to debug multiple times the particular test `TimeSpanWithMinTimeUnit`

When I right click a test in Test Explorer and choose to run or debug the selected test, it takes several minutes to discover all tests before the test actually runs. Is there a way to speed things up?

    [xUnit.net 00:03:50.7515043] Humanizer.Tests: Discovered test case 'ReturnsLargestMetricPrefixLargerThanZero' (ID = '8c3a2f7fda13b5b040f466c958bfd191e9519d12', VS FQN = 'Humanizer.Tests.Bytes.ToStringTests.ReturnsLargestMetricPrefixLargerThanZero')
    [xUnit.net 00:03:50.7648850] Humanizer.Tests: Discovered test case 'ReturnsLargestMetricPrefixLargerThanZeroForNegativeValues' (ID = '8df99e81db618caf9b7da929fae69b130b4d5446', VS FQN = 'Humanizer.Tests.Bytes.ToStringTests.ReturnsLargestMetricPrefixLargerThanZeroForNegativeValues')
    [xUnit.net 00:03:50.7761650] Humanizer.Tests: Discovered test case 'approve_public_api' (ID = '837d518deba1bc8dd3fede2920421248ccf0831b', VS FQN = 'Humanizer.Tests.ApiApprover.PublicApiApprovalTest.approve_public_api')
    [xUnit.net 00:03:50.7769602]   Discovered:  Humanizer.Tests (running 7331 test cases)
    ========== Discover test finished: 14657 found (0:03:51,133111) ==========
    ------ Run test started ------
    [xUnit.net 00:00:01.6632041]   Starting:    Humanizer.Tests (parallel test collections = on, max threads = 4)
    [xUnit.net 00:00:02.4071970]   Finished:    Humanizer.Tests
    ========== Run test finished: 1 run (0:00:06,7376737) ==========

**Comment by onovotny** [comment]
Updating to xUnit 2.3-beta should help, but overall there's not much we can do.
