### ISSUE TITLE
English verb (Past Participle) tense conversion "x" => "xed" feasibility?

### ISSUE THREAD

**Issue by dsaf** [Humanizr/Humanizer#616]
Is it feasible to do this sort of conversion? Would there be too many exceptions? Too English-specific?

```
"Verify" => "Verified"
"Do" => "Done"
"Cancel" => "Cancelled"
"Approve" => "Approved"
```

http://www.englishpage.com/irregularverbs/irregularverbs.html

Use case is command-driven or workflow type of applications where an action results in a state change.

**Comment by hazzik** [comment]
Same as #58, see conversation there
