### ISSUE TITLE
int64 support 

### ISSUE THREAD

**Issue by AlexKeySmith** [Humanizr/Humanizer#622]
Hi it would be great to have int64 support for ToWords() to add descriptions to massive numbers.

Keep up the good work!

**Comment by aloisdg** [comment]
Wiki: [Names of large numbers](https://en.wikipedia.org/wiki/Names_of_large_numbers#Standard_dictionary_numbers)

For example: `9,223,372,036,854,775,807` is ` nine quintillion, two hundred twenty-three quadrillion, three hundred seventy-two trillion, thirty-six billion, eight hundred fifty-four million, seven hundred seventy-five thousand, eight hundred seven`.

A idea could be to convert the big number step by step then call `ToWords()` when we are small enough.

**Comment by dnordquist** [comment]
I might be wrong about this, but I see that ToWords() *does* exist on `long`, so it seems like this issue can be closed?

**Comment by SimonCropp** [comment]
@dnordquist thanks for the followup
