### ISSUE TITLE
Wrongful commit to master. What to do?

### ISSUE THREAD

**Issue by aloisdg** [Humanizr/Humanizer#623]
Hello,

After reading the french part of some code. I took the initiative to clean a bit the code directly in the GitHub website and [commit](https://github.com/Humanizr/Humanizer/commit/eb110e56c72b3529cf9a7f649f499499315482a7). I thought that it will create a patch-1 and forgot that I am able to change master directly ! Instead of PR the code was ship directly into master ! The CI run it (and since [AppVeyor failed](https://ci.appveyor.com/project/onovotny/humanizer/build/1.0.277) and I am glad it did!). This wrong commit shouldnt go to far. I am not able to revert it right now (cant find the function on the website and I cant clone where am I) and I am not sure about what to do. I hope this move wasn't to harmful. Is it possible to remove right to commit to some branch? If so I would like to limit myself to dev. I don't need more so I shouldn't have more.

Thank you. Sorry for the trouble. 😢 

Ping: @onovotny @mexx @hazzik

**Comment by onovotny** [comment]
Just reversed -- https://github.com/Humanizr/Humanizer/tree/2f4c37915e51cffa549ce45a0ddeddccd05ef4ee

Some tools like SourceTree allow you to reverse a commit (they do an inverse commit).

**Comment by aloisdg** [comment]
@onovotny Thank you.
