### ISSUE TITLE
Humanize Collections with commas only?

### ISSUE THREAD

**Issue by softwareguy74** [Humanizr/Humanizer#624]
I want a collection to show as "Item 1, Item 2, Item 3" without a string seperator at the last word such as "and" or "or".  I tried collection.Humanize("") but that produces an extra space between the last comma and value.

Can we get this feature added?

**Comment by softwareguy74** [comment]
When will this make it to nuget?

**Comment by onovotny** [comment]
@markpastuszka, can you please submit a PR and include a unit test? would love to get this into 2.2 when we ship it in a couple weeks!

**Comment by hazzik** [comment]
I do not see the reason why this shall be in Humanizer.

What is the difference with the following code:
```
string.Join(", ", collection)
```
?

**Comment by onovotny** [comment]
@hazzik fair enough, @softwareguy74 is there something more than that? Seems like a simple workaround?

**Comment by softwareguy74** [comment]
Because it's already in there.  It just needs to be fixed.

**Comment by SimonCropp** [comment]
Seems there is a simple alternative
