### ISSUE TITLE
Preventing "extension pollution" on base types....

### ISSUE THREAD

**Issue by natiki** [Humanizr/Humanizer#629]
Hi,

I have just come across Humanizer and it looks great. However as I contemplate folding this into a larger more complex code base I would like to "know" that I am utilizing a Humanizer extension rather than one that comes from elsewhere. 

However I see that some methods come straight off the base type and some via the Humanize() static instance.

```c#
        "Some String".Humanize().Transform();
        "Some String".Transform();
```
Is there a way to *not* have .Transform() (And any other direct extensions.) available?

**Comment by natiki** [comment]
Bump!

**Comment by aloisdg** [comment]
I am not sure about my answer, but since you don't have something better for now, I will share an idea.

You could stop using Humanizer with `using Humanizer;` and to rely on `Humanizer.Transform("Some String");`.

**Comment by SimonCropp** [comment]
the solution provided by @aloisdg is the correct way to handle this
