### ISSUE TITLE
Add project to up-for-grabs.net

### ISSUE THREAD

**Issue by onovotny** [Humanizr/Humanizer#635]
https://github.com/up-for-grabs/up-for-grabs.net

**Comment by MaStr11** [comment]
There is already an entry for [humanizer.yml](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/humanizer.yml), but it points to [https://github.com/MehdiK/Humanizer](https://github.com/MehdiK/Humanizer).

**Comment by hazzik** [comment]
https://github.com/up-for-grabs/up-for-grabs.net/pull/615
