### ISSUE TITLE
XBuild not including humanizer resources

### ISSUE THREAD

**Issue by brandonrisell** [Humanizr/Humanizer#639]
If I build a xamarin application in Xamarin Studio using xbuild, no humanizer language resources are included. If I build the same project in Visual Studio or Visual Studio for Mac with msbuild, then it includes the language resource assemblies in their respective directories.

I've created a quick xamarin project that highlights this issue: https://github.com/brandonrisell/HumanizerRepro

Is there anything I can do to have xbuild include the language resource assemblies?

**Comment by brandonrisell** [comment]
As an update, I tracked it to this bug:
https://bugzilla.xamarin.com/show_bug.cgi?id=38476

With xbuild now deprecated and Microsoft supporting MSBuild via Visual Studio for Mac, I'll close this.

**Comment by Dids** [comment]
Hmm, I'm still seeing this with Xamarin.Forms and on Visual Studio for Mac:
```
Xamarin.iOS: Unable to locate assembly 'Humanizer.resources' (culture: 'fi')
```

**Comment by brandonrisell** [comment]
Hmm, might be unrelated? Do you see an `fi-FI` directory in your `bin` directory after a build?
