### ISSUE TITLE
Pluralize causes crash

### ISSUE THREAD

**Issue by matthewblott** [Humanizr/Humanizer#646]
I spent a while tracking down a bug today and found it was caused by the Pluralize extension method being called in my data access layer (I ran an isolated test with a console app to confirm).

My scenario:

macOS
NET Core 1.1
Humanizer 2.2.0

I reverted to Humanizer 2.1.0 and the issue disappeared. This is fine for me but thought I'd log this as an issue :-)

**Comment by MehdiK** [comment]
Thanks for reporting the bug. Could you send us your test please (if you still have it around)?

**Comment by matthewblott** [comment]
I just revisited my code and can't find the test. I can tell you it was the Pluralize method that was causing the crash but I stopped working with NET Core 1.1 some time ago and have been using NET Core 2.0 which works okay with Humanizer 2.2.0 for me. There might still be an issue with NET Core 1.1.

**Comment by MehdiK** [comment]
Thanks for the response. I'd imagine most people would've migrated to Core 2 by now. So I'm going to close the issue. Happy to revisit it if it pops up again and can be reproduced.
