### ISSUE TITLE
Spanish Culture issue 

### ISSUE THREAD

**Issue by ahidmanja** [Humanizr/Humanizer#650]
When I am trying to get ordinal numer in spanish I am getting the cardinal instead.

string Final = 50.ToOrdinalWords(spanishCultureInfo);
// Final = "Cincuenta" while it should be  "quincuagésimo"

**Comment by hazzik** [comment]
Which exact flavor of Spanish are you talking about? Is it something common for all languages or only for few?

**Comment by hangy** [comment]
The `SpanishNumberToWordsConverter` seems to make some incorrect assumptions for Spanish ordinals >10: https://www.spanishdict.com/guide/ordinal-numbers-in-spanish

**Comment by mihemihe** [comment]
> Which exact flavor of Spanish are you talking about? Is it something common for all languages or only for few?

As per my understanding, ordinal and cardinal numbers are the same across all Spanish flavors. (Spanish speaker from Spain here).



> The SpanishNumberToWordsConverter seems to make some incorrect assumptions for Spanish ordinals >10:

Yes, it does seems only first 10 simple forms are implemented. 

I have found this article where one Spanish university has dissected the official rules (from RAE) and should not be difficult to implement. There are a bunch of exceptions, and they fail in their online converter to go further than 1,000,000th, but up to this point the rules are clear. 

http://tip.iatext.ulpgc.es/es/ordinales

I am going to do some research and testing and I will update shortly.

**Comment by mihemihe** [comment]
@hangy @hazzik @MehdiK  I got a question, regarding what is the expected or preferred method of implementing ordinal numbers. This is related to some quirks of Spanish language and I guess you, as experienced members of this solution, could help me to decide what is best.

This is related to 1st and 3rd in Spanish. There are two forms of saying 1st: primer and primero/a

Examples:

**The query returned the first result** = La consulta devolvió el **primer** resultado
**He finished the race first** = Terminó el **primero** 
**I live in the third floor** = Vivo en el **tercer** piso
**Which book, the third one?** = ¿Que libro, el **tercero**?

There is no way to implement both methods at the same time without allowing the developers to express their intents overloading somehow the method. However this is fairly trivial to solve in any code using the library adding exceptions to the result returned, so in my opinion it would be better to implement the version matching the format in both, feminine and masculine, which is primero/primera and tercero/tercera. 

This is how I weighed 	both options:	

| **Primero/Tercero**  | **Primer/Tercer** |
| ------------- | ------------- |
| Easier to fix on code using the library +1 | More difficult -1  |
| This form occurs in less occasions -1 | This form occurs less +1 |
| It is more coherent with Masc/Feme forms +1| Less coherent -1 |
| Breaks current implementations -1*| Does not break current implementations +1* |

*The option I suggest breaks current implementations, but given that the existing solution is extremely limited (only 1 to 10) I guess it is not widely used at this moment. Maybe adding a some clarification in the release notes for next version would be enough? 

This also require changing the Unit tests for 1st and 3rd.

**Comment by MehdiK** [comment]
Thanks for explaining.

Just to avoid any confusion, are you saying that the current implementation
is wrong because it only uses primer and that what you're suggesting will
also be wrong as it will only use primero/a? If yes, what would be the
benefit of introducing a breaking change for Spanish users?

**Comment by mihemihe** [comment]
> Just to avoid any confusion, are you saying that the current implementation
> is wrong because it only uses primer and that what you're suggesting will
> also be wrong as it will only use primero/a? If yes, what would be the
> benefit of introducing a breaking change for Spanish users?
@MehdiK 

Both forms are correct in Spanish language, but using one or the other depends on the context they are used, so none of the implementations will be 100% correct in all cases. The developer using this method would expect and overloaded method to chose one form or the other. But because there is no such overload, I suggest going to the most coherent solution, which is standard for both genders, and simplifies the dev task of amending the return value to his/her needs.

I have the code and unit tests ready and I am figuring out how to do the pull request properly. This is the first time I commit in a public repo that is not documentation. :-)

**Comment by MehdiK** [comment]
Makes sense.

Awesome. Create a local branch, commit your changes to it, do a git push
origin your-branch-name, open your fork on GitHub, it asks you if you want
to create a pull request for your branch. GitHub guides you through the
rest.

Just a couple of things: make sure your code is based on the latest (no
merge conflicts) and your tests are green.

**Comment by mihemihe** [comment]
@MehdiK I guess I am doing something wrong. 

I "Create a local branch from..."
https://imgur.com/eXRWqsS

I select origin/dev and type the name of the branch. 

https://imgur.com/imSF172

I do all changes, then I commit all. All in the local branch 

https://imgur.com/sCqTZah

Changes commited in local branch 

https://imgur.com/bn4yPz5

then I try to push that branch but I get an error . 

https://imgur.com/VPP6TWe

https://imgur.com/rbB02Sx
