### ISSUE TITLE
ToWords for chinese culture is not working

### ISSUE THREAD

**Issue by rgm97531** [Humanizr/Humanizer#660]
Hi,

I am trying to use Humanizer 2.2.0.0 in .Net application (framework version 4.6.1 )  to to print Chinese words for numbers with the following code.
 **100.ToWords(new CultureInfo("zh-CN"));**

But the output is always 100. Chinese words are not printed.

Please let me know if it is a bug or I am missing something.

**Comment by hangy** [comment]
Looking at https://github.com/Humanizr/Humanizer/tree/83008235bd5ce1a4c2168183fc00915b8d86aca2/src/Humanizer/Localisation/NumberToWords, it does not look like Chinese is implemented.

**Comment by SimonCropp** [comment]
Chinese has since been implemented
