### ISSUE TITLE
Project doesn't load on Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by mshulman** [Humanizr/Humanizer#661]
Clean install of Windows 10 with clean install of Visual Studio 2015 Update 3.

\\Mac\Home\Downloads\Humanizer-dev\Humanizer-dev\src\Humanizer\Humanizer.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  \\Mac\Home\Downloads\Humanizer-dev\Humanizer-dev\src\Humanizer\Humanizer.csproj

**Comment by MehdiK** [comment]
The solution is updated to VS2017. The upgrade from VS2015 is free though.
