### ISSUE TITLE
Camelize() fails on empty/null strings

### ISSUE THREAD

**Issue by jpobst** [Humanizr/Humanizer#663]
AOORE with this code:

`"".Camelize()`

ANE with this code:

`((string)null).Camelize()`

**Comment by hangy** [comment]
I think that most of Humanizer's string extensions will throw an ArgumentNullException for null strings, so that could be expected for `Camelize`, too. The ArgumentOutOfRangeException needs to be prevented, though.

**Comment by MehdiK** [comment]
Fixed in #664. Thanks.
