### ISSUE TITLE
"human".Pluralize() == "humen"

### ISSUE THREAD

**Issue by emilmuller** [Humanizr/Humanizer#666]
Oh, the irony :)

**Comment by MehdiK** [comment]
666! Hmmm, should I trust this issue?! 

Joke aside, the fix would be quite simple. Did you want to send us a PR?

**Comment by BrownCasey** [comment]
Looks like a good first issue. I'll take it if OP doesn't want.

**Comment by MehdiK** [comment]
Great. Don't forget the test please.
