### ISSUE TITLE
Humanizer.tests.uwp and Humanizer.tests.uwp.runner don't load on Visual Studio 2017

### ISSUE THREAD

**Issue by mshulman** [Humanizr/Humanizer#667]
dev\src\Humanizer.Tests.Uwp\Humanizer.Tests.Uwp.csproj : error  : Object reference not set to an instance of an object.

dev\src\Humanizer.Tests.Uwp.Runner\Humanizer.Tests.Uwp.Runner.csproj : error  : Object reference not set to an instance of an object.

It's not clear to me what the errors are in these files, but they don't load on Visual Studio 2017

**Comment by onovotny** [comment]
Do you have the UWP workload installed?

**Comment by onovotny** [comment]
I've split these out into a separate solution as they're really only needed for validation tests. The current `Humanizer.sln` no longer contains them.
