### ISSUE TITLE
How do I make humanizer not display milliseconds?

### ISSUE THREAD

**Issue by PalashSachan** [Humanizr/Humanizer#669]
i don't want that last milliseconds in my result

how do i remove this?

Is there any method to do that or to remove that last milliseconds part

I am using Humanizer to convert Timespan to human readable time

see the image below
[image](https://i.imgur.com/Bi324X2.png)

i am doing it like this 👍 

Console.WriteLine("Time Remaining :- {0}", timeRemaining.Humanize(5));

## please help
thanks

and i am really **## sorry** if this kind of questions are not supposed to be asked here like this

**Comment by MehdiK** [comment]
So you want to see the milliseconds but don't want to see `milliseconds` word in the end?! Humanizer doesn't support that. You'd have to do it yourself using `substring` or `remove`.

No problems with the question. Happy to help.

**Comment by PalashSachan** [comment]
yeah..no problem..i did that like this 

`private static string RemoveMilliSeconds(string s)
        {
            return s.Contains("milliseconds") ? s.Substring(0, s.LastIndexOf(',')) : s.Contains("no time") ? "Calculating..." : s;
        }`

and thanks for this great Library anyway :)
