### ISSUE TITLE
plural of personnel is personnel itself

### ISSUE THREAD

**Issue by ahmadalli** [Humanizr/Humanizer#672]
plural of personnel is personnel itself but `Pluralize` returns `personnels`

**Comment by MehdiK** [comment]
Thanks for reporting this. Did you want to submit a PR for it? It's a very simple fix. Here's a recent example: https://github.com/Humanizr/Humanizer/pull/670/files

**Comment by ahmadalli** [comment]
I’ve send a PR

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MehdiK** [comment]
Thanks for the PR. Merged. Will release soon.
