### ISSUE TITLE
To.TitleCase not working on CamelCase

### ISSUE THREAD

**Issue by alski** [Humanizr/Humanizer#676]
Hi, this might just be a bad assumption on my part but I was expecting that

"someValue".Transfrom(To.TitleCase).ShouldBe("SomeValue");

//but is
"someValue".Transfrom(To.TitleCase).Equals("Somevalue");

**Comment by MehdiK** [comment]
Title transformations do NOT Humanize the input before changing the casing. If you want that outcome, you'd have to humanize it first and then dehumanize it again.
