### ISSUE TITLE
On-Board project to the .NET Foundation

### ISSUE THREAD

**Issue by onovotny** [Humanizr/Humanizer#682]
We're getting ready to bring the project into the .NET Foundation, but before we
do we need to do the following:

## Getting into the .NET Foundation
- [x] Make sure the project has a good name that is easy to remember and 
 spell. Check that it doesn't [conflict with another existing project](http://ivantomic.com/projects/ospnc/)
- [x] Make sure the people involved in the project want to join the .NET Foundation
- [x] Make sure the project has a clear understanding about how it accepts contributions and the process
     it follows when selecting new committers to the project.
- [x] [Register an interest](https://dotnetfoundation.org/get-involved) in joining the .NET Foundation
- [x] Work with the .NET Foundation to fill out an On-Boarding Questionaire
- [x] .NET Foundation sends out completed questionaire to .NET Foundation Advisory Council for comments
- [x] .NET Foundation Executive Director submits new project proposal to the .NET Foundation Board
- [x] Configure a CI build for the project and ensure build status badges are available from the README

## Once accepted into the .NET Foundation
- [x] Sign the contribution / assignment agreement
- [x] Agree a date to move into the .NET Foundation
- [ ] Prepare a guest blog post announcing the move on the .NET Foundation Blog
- [x] Read the [code of conduct](https://dotnetfoundation.org/code-of-conduct), 
      [link to it in your code](be-nice.md) and 
      understand what to do if you are concerned about any behaviour or have
      concerns reported to you.
- [ ] Tell the world we have joined!
- [x] Get CLA Automation enabled to ensure contributors can easily sign the 
      [Contribution License Agreement](https://cla2.dotnetfoundation.org/cladoc/net-foundation-contribution-license-agreement.pdf)
- [x] Send a PR to add the Project into the .NET Foundation 
      [list](https://github.com/dotnet/home/tree/master/projects)
- [x] Ensure the repo contents are up to date with [.NET Foundation guidance](repo-guide.md)
- [x] Review the [README guidance](readme-guide.md) and update if necessary
- [x] If applicable [update the LICENSE file](copyright.md) to show Copyright has been assigned to the .NET Foundation
      and look to update any file headers.
- [x] If applicable, update any copyright statements in websites owned by the project to reflect 
      assignment to the .NET Foundation
- [x] If applicable, update any websites associated with the project to include
      "Supported by the <a href="https://dotnetfoundation.org">.NET Foundation</a>" or
      similar link back to the .NET Foundation in the footer. If applicable, please
      include image links from [our swag repo](http://github.com/dotnet/swag). (We think a link in the footer using the horizontal logo looks very nice.)
- [x] [Sign up for Project Leader news](http://eepurl.com/bOCfJP)
- [x] Configure any resources requested from the .NET Foundation (SSL Certs, Code Signing,
      Secret Management, Build Servers etc)

**Comment by onovotny** [comment]
@MehdiK do you want to sign up for the project leader news (link above?) Also, Would you be interested in writing up that guest blog post announcing Humanizer joining the foundation or should I do that?

**Comment by MehdiK** [comment]
I've already signed up to the leader news.

You initiated this effort. You should write the guest blog.

**Comment by onovotny** [comment]
Cool, will write something up. BTW, I switched the CI builds to the dotnetfoundation account on AppVeyor; you should still have access to it. If not, lmk and I'll fix it.
