### ISSUE TITLE
Humanize Enum flags with flag "NONE" (0) flag

### ISSUE THREAD

**Issue by Kricke242** [Humanizr/Humanizer#683]
Hello!

Assume the enum:
```
[Flags] public enum FileAccess { 
[Description("None")]
None = 0, 
[Description("Read")]
Read = 1, 
[Description("Write")]
Write = 2,
[Description("Delete")]
Delete = 4
}
```
Then the following will return the correct "Read" string:

`FileAccess.Read.Humanize();`

But the following will give "None, Read and Write" string:

`(FileAccess.Read | FileAccess.Write).Humanize();`

Which is, while not technically incorrect since HasFlag(0) is true for all flags, not always useful (and you don't get "None, Read" when the value is defined).

The code in EnumHumanizeExtensions.cs does not remove zero values, if it is a BitFieldEnum and has multiple selected bits.
Is it possible to add a parameter to the function to remove the "NONE" (0) value if other flags are set?
Just an example below, I did not test the code.
```
public static string Humanize(this Enum input, bool removeZeroValueFromMultipleFlagsResult = false)
{
//...
   if (IsBitFieldEnum(enumTypeInfo) && !Enum.IsDefined(enumType, input))
            {
                return Enum.GetValues(enumType)
                           .Cast<Enum>()
                           .Where(e => input.HasFlag(e) && (!removeZeroValueFromMultipleFlagsResult || Convert.ToInt32(e) != 0))
                           .Select(e => e.Humanize())
                           .Humanize();
   }
//...
}
```
I think this is what many expects? Adding all possible combinations in the enums with their own description isn't really viable either. 

Thank you for an excellent library! :-)

**Comment by MehdiK** [comment]
Great idea. Do you want to send a PR?

**Comment by Kricke242** [comment]
Hi. Yes, perhaps I can send a PR. I don't have the time to write it right now, though. But I'll get back to it.
Do you think

> public static string Humanize(this Enum input, bool removeZeroValueFromMultipleFlagsResult = false)

is ok, in order to default to the old behaviour?
