### ISSUE TITLE
Humanize collection with Func<T, object> displayFormatter

### ISSUE THREAD

**Issue by jnm2** [Humanizr/Humanizer#692]
BCL printing and formatting APIs such as string.Join accept object instances as well as strings. Even C#'s string concatenation reinforces the concept of removing superfluous `?.ToString()` invocations.

Ever since I discovered that I could write `collection.Humanize(item => item.Name)`, I've been using that instead of `collection.Select(item => item.Name).Humanize()`. The consistency breaks down when you want to use something else though. I wish I didn't have to add `.ToString()` in `collection.Humanize(item => item.Date.ToString())`.

What do you think? Would a convenience overload make sense?

https://github.com/Humanizr/Humanizer/blob/065874dfd6b1972a82aa77f36286593c69e5fd88/src/Humanizer/CollectionHumanizeExtensions.cs#L23-L28

```diff
namespace Humanizer
{
    public static class CollectionHumanizeExtensions
    {
        public static string Humanize<T>(this IEnumerable<T> collection);
        public static string Humanize<T>(this IEnumerable<T> collection, Func<T, string> displayFormatter);
+       public static string Humanize<T>(this IEnumerable<T> collection, Func<T, object> displayFormatter);
        public static string Humanize<T>(this IEnumerable<T> collection, string separator);
        public static string Humanize<T>(this IEnumerable<T> collection, Func<T, string> displayFormatter, string separator);
+       public static string Humanize<T>(this IEnumerable<T> collection, Func<T, object> displayFormatter, string separator);
    }
}
```

**Comment by onovotny** [comment]
I like the idea, long as we can properly resolve the overloads.

**Comment by jnm2** [comment]
I can't think of a scenario that would cause overload resolution to fail.

**Comment by onovotny** [comment]
Can you please do a PR with appropriate unit test coverage and doc updates?

**Comment by jnm2** [comment]
Oh, `.Humanize(item => null)` will break. Are you okay with that?

**Comment by jnm2** [comment]
Wait, no it won't. https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwGFKBvS/D/dzmwgFnwAVCAGdgACgCU3DmwqcF+ALLip+ALwA+fADsArgBsDk8vM4BfGVzMcrvbAJXYArAB4A9gCMAVhADGwNoAhtI2+HIKlhR2tA7K4i6uxLjBoQoRFpTmQA===
