### ISSUE TITLE
Sort strings ignoring culture specific article word prefixes

### ISSUE THREAD

**Issue by wldevries** [Humanizr/Humanizer#694]
Let's say we have the following list, it would be great if we could sort it while ignoring article words like the and a:
```c#
var items = new [] { "Banana", "Fork", "The apple" };
var sorted = items.OrderBy(i => i.HumanizeSortPrefixes());
sorted.ForEach(i => Console.WriteLine(i));
```
with output:
```
The apple
Banana
Fork
```
I'm not really sold on the method name though..

**Comment by christopherie** [comment]
I think this is very interesting. I would like to give this a try.

**Comment by SimonCropp** [comment]
@wldevries @christopherie whats the use case for this?

**Comment by wldevries** [comment]
It seems useless to me now.

**Comment by SimonCropp** [comment]
@wldevries thanks for getting back to us. will close this one for now

**Comment by hazzik** [comment]
This was already possible, but not in the Linq.
