### ISSUE TITLE
ToWords bug with negative sign (Arabic culture)

### ISSUE THREAD

**Issue by EMostafaAli** [Humanizr/Humanizer#698]
I noticed that Arabic culture implementation of ToWords doesn't deal with negative numbers. I mean in English implementation we can see 
```
if (number < 0)
                return string.Format("minus {0}", Convert(-number));
```
But the same can't be found in Arabic version. Is there a specific reason? if not, I will be glad to fix it.

**Comment by AdhamAwadhi** [comment]
**I fixed this.** I will create PR as soon as possible.

**Comment by EMostafaAli** [comment]
@AdhamAwadhi , I would rather use the Arabic word "ناقص" instead of "سالب".

**Comment by AdhamAwadhi** [comment]
@EMostafaAli , I committed with that change. Thank you
