### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by Emixam23** [Humanizr/Humanizer#701]
Hey !

I was wondering if by any chance if, with your nuget, I can translate country name into a given language?

Because I am trying to display a list of countries based on the device language, like the following:

- ES-es
  - España
  - Estados Unidos
  - Francia

- FR-fr
  - Espagne
  - Etat-Unis
  - France

- US-en
  - France
  - Spain
  - USA

Your library is the best I found for the moment, so that's why I was wondering if I could achieve a such a things with your nuget :) Also, I have either the english name or the ISO code, either for each country or each device language

Thanks !

**Comment by Jarrich** [comment]
I don't believe that translating certain values in within scope of this project.
