### ISSUE TITLE
Warnings when building UWP min/target FCU (16299)

### ISSUE THREAD

**Issue by allanrsmith** [Humanizr/Humanizer#708]
Create a new Blank App (Universal Windows Platform)
Add Humanizer via Manage Nuget Pacakages.

From VS Command Line run : `msbuild <sln file>`

OUTPUT:
(_GenerateProjectPriFileCore target) ->
  GENERATEPROJECTPRIFILE : warning PRI257: 0xdef00522 - Resources found for language(s) 'en,af,ar,bg,bn-bd,cs,da,de,el,
es,fa,fi-fi,fr,fr-be,he,hr,hu,id,it,ja,lv,nb,nb-no,nl,pl,pt,ro,ru,sk,sl,sr-latn,sv,tr,uk,uz-cyrl-uz,uz-latn-uz,vi,zh-cn
,zh-hans,zh-hant' but no resources found for default language(s): ''. Change the default language or qualify resources with the default language. http://go.microsoft.com/fwlink/?LinkId=231899
GENERATEPROJECTPRIFILE : warning PRI263: 0xdef01051 - No default or neutral resource given for 'Humanizer.Properties.
Resources/TimeSpanHumanize_MultipleDays_DualTrialQuadral'. The application may throw an exception for certain user configurations when retrieving the resources.

**Comment by onovotny** [comment]
This `Resources/TimeSpanHumanize_MultipleDays_DualTrialQuadral'. The application may throw an exception for certain user configurations when retrieving the resources.` should be fixed in the latest. The first part is a tooling bug with MarkPri, afaik.

**Comment by aelij** [comment]
We're getting a similar error with the latest version:

```
GENERATEPROJECTPRIFILE : warning PRI263: 0xdef01051 - No default or neutral resource given for 'Files/Humanizer.resources.dll'. The application may throw an exception for certain user configurations when retrieving the resources.
```

Using the latest (17763) SDK.

**Comment by onovotny** [comment]
@aelij do you have a repro for that PRI263?

**Comment by aelij** [comment]
@onovotny It's part of a rather large project. I will try to create a small repro.

**Comment by aelij** [comment]
[PRI263_repro.zip](https://github.com/Humanizr/Humanizer/files/2528925/PRI263_repro.zip)

Just run `build.cmd` from a VS command prompt.
