### ISSUE TITLE
Add option to return full words instead of abbreviations for ByteSize objects.

### ISSUE THREAD

**Issue by icnocop** [Humanizr/Humanizer#719]
I'd like the ability to explicitly return full words instead of abbreviations for ByteSize objects.

For example,
Current behavior:
```
7.Bits().ToString();         // 7 b
8.Bits().ToString();         // 1 B
```
Feature request:
```
7.Bits().Humanize().ToFullWords(); // 7 bits
8.Bits().ToFullWords();            // 1 Byte
```
Or maybe we can pass configuration options like suggested in https://github.com/Humanizr/Humanizer/issues/508
```
7.Bits().Humanize(new HumanizeOptions{ FullWords = true }); // 7 bits
8.Bits().Humanize(new HumanizeOptions{ FullWords = true }); // 1 Byte
```

Thank you.

**Comment by Ashera138** [comment]
I'd like to give this a shot. 👍 I'll let you know if I have any questions or when I have a pr ready if that's alright with you.

**Comment by Ashera138** [comment]
I'm heading out of town for a couple of days, but I'll pick this back up when I get back. :)

**Comment by Ashera138** [comment]
Alright, PR is ready. Let me know if there are any changes that need to be made! 😃

**Comment by Ashera138** [comment]
Alright, PR is submitted. Let me know if there are any changes that need to be made! 😃

**Comment by Ashera138** [comment]
This can be closed now. 🏷
