### ISSUE TITLE
Add support for non-integer types with ToQuantity

### ISSUE THREAD

**Issue by AdamDawes** [Humanizr/Humanizer#722]
I'm writing an application that displays numbers in the form "1 hour", "2 hours", etc. and so using the `ToQuantity` method looked perfect. However the number of hours in this case is not a whole number, as the application supports half-hours too. This means I can't use `ToQuantity` as it only supports `int` or `long` as parameter types.

Could we have additional overloads to support `decimal`, `double` etc. parameter types for this method?

**Comment by niallermoran** [comment]
I have created a simple solution for this that accepts doubles and decimals, but only supports ShowQuantityAs.Numeric, e.g. 0.2 hour will return 0.2 hours.

If this works I can submit a PR
