### ISSUE TITLE
.NET 4.5 support dropped?

### ISSUE THREAD

**Issue by crowbarsolutions** [Humanizr/Humanizer#731]
The latest nuget package no longer has .NET 4.5 listed in the dependencies, causing the package to download a bunch of .NET Standard libraries when installed. Was this intentional, or were changes made that brake compatibility with projects using the full .NET framework?

**Comment by JobaDiniz** [comment]
Same issue here :cry:

**Comment by MalcolmJohnston** [comment]
In our use case we are using Humanizer in conjunction with the T4 templates to generate boiler plate code.  Unfortunately T4 has been somewhat abandoned (so maybe we should use a different tool!) and cannot reference .NET standard dlls.

Could Humanizer not be multi-targeted and provide a full fat dll as well as netstandard?

**Comment by onovotny** [comment]
There is no `net45` specific code in Humanizer; there's a `netstandard1.0` version for older frameworks, though the dependency graph is far better with `net461` and higher, which will use the `netstandard2.0` version. The `netstandard2.0` version does not have any dependencies and is the recommended version.

**Comment by JobaDiniz** [comment]
So, nothing will be done, is that it?
I must say, when I update to the latest version several netstandard
packages are installed and that's not useful, that's not needed for .net4.5

**Comment by onovotny** [comment]
There's nothing to do here. Adding a `net45` target bloats the size of the package. The recommended option to minimize dependencies is to target `net461` or higher. There's very little reason to target NET 4.5. It is out of support and may have 0-days in the wild.
