### ISSUE TITLE
Humanizer 2.4.2 introduced dependency on System.Data.Common that caused havoc

### ISSUE THREAD

**Issue by jfrank14** [Humanizr/Humanizer#733]
The other day I did a routine package upgrade from 2.2.0 to 2.4.2 and my site completely broke, failing to load the correct version of System.Data.Common.

Since this was part of a number of updates, and since the error didn't mention Humanizer, it took me literally days of painstaking troubleshooting to determine that 2.4.2 has a dependency on System.Data.Common.dll, and furthermore this file has some sort of versioning issue that made it impossible to find a version that would not cause conflict.

For now, I have reverted to 2.2.0, which doesn't have this dependency (and makes me wonder why it would suddenly be necessary), and I live in fear of someone accidentally upgrading to it.

Can anyone comment on what's going on here?

**Comment by hangy** [comment]
Where do you see this dependency? I can't find any reference to it. Humanizer >=2.3 does not provide PCL any more and uses .NET Standard instead. It only depends on .NET Standard 1.6 or .NET Standard 2.0 (and some development dependency NuGet packages).
