### ISSUE TITLE
v2.4.2 blocks compiling UWP project with .NET native tool chain (Release mode)

### ISSUE THREAD

**Issue by nvborisenko** [Humanizr/Humanizer#734]
Steps to reproduce:
1. Add package Humanizer.Core **v2.4.2**  into UWP project
2. Build project in Release configuration

Result:
Project cannot be compiled.
`C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Internal compiler error: Specified cast is not valid.`

Workaround:
Downgrade package to v2.3.3

**Comment by onovotny** [comment]
What version of the UWP meta-package age you using, are you on the latest, 6.1.5?

What is the TargetPlatformVersion and Min Version?

**Comment by nvborisenko** [comment]
UWP 6.1.5
Target 1803 (Build 17134)
Min 1803 (Build 17134)
VS 15.7.5

**Comment by onovotny** [comment]
Thanks, looking into it.

**Comment by onovotny** [comment]
@nvborisenko do you have a small repro you could either attach or point to? The .NET Native team is having trouble reproducing this.

**Comment by nvborisenko** [comment]
@onovotny  attached 
[AppIssue734.zip](https://github.com/Humanizr/Humanizer/files/2318943/AppIssue734.zip)

Also actual nuget package with issue is `Humanizer.Core.ru`, not `Humanizer.Core`.

**Comment by YZahringer** [comment]
Same issue, no problem with v2.3.3

**Comment by Paradoxon101** [comment]
Same issue, no problem with v2.3.3

**Comment by SimonCropp** [comment]
from this error 
```
C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Internal compiler error: Specified cast is not valid.
```

it would seem a bug in the tooling. I suggest raising it with the .net sdk team
