### ISSUE TITLE
zh-Hans doesn't work on xamarin.forms 3.0

### ISSUE THREAD

**Issue by anhuynhBT** [Humanizr/Humanizer#736]
Hi, Teams

I'm trying to install Humanizer.Core.zh-Hans and Humanizer.Core packages for my project. But Humanizer.Core.zh-Hans doesn't work. It does not show error or warning. It always shows English.
I'm using xamairn.forms 3.0 and xamarin.android latest version. Do I need any config ?
Thanks

**Comment by davidortinau** [comment]
@GreenRock can you share your project here or a small sample that demonstrates the issue with Xamarin.Forms?

**Comment by SimonCropp** [comment]
closing due to no response
