### ISSUE TITLE
Passing the language/culture to be used when calling transform

### ISSUE THREAD

**Issue by ofirgeller** [Humanizr/Humanizer#751]
I should be able to specify the language in someway besides changing the culture of the thread.

**Comment by JPVenson** [comment]
+1

**Comment by AKTheKnight** [comment]
@ofirgeller @JPVenson Can I ask exactly which methods you want to be able to pass the language/culture to? From what I can see, only "ToLowerCase" actually needs the culture.

I can definitely look at how we can add a culture parameter to help in this situation though.

**Comment by JPVenson** [comment]
`InflectorExtensions.Pluralize` and `InflectorExtensions.Singularize` are the methods in question. They use the Vocabularie.Default static. 
```
/// <summary>
/// Pluralizes the provided input considering irregular words
/// </summary>
/// <param name="word">Word to be pluralized</param>
/// <param name="inputIsKnownToBeSingular">Normally you call Pluralize on singular words; but if you're unsure call it with false</param>
/// <returns></returns>
public static string Pluralize(this string word, bool inputIsKnownToBeSingular = true)
{
    return Vocabularies.Default.Pluralize(word, inputIsKnownToBeSingular);
}

/// <summary>
/// Singularizes the provided input considering irregular words
/// </summary>
/// <param name="word">Word to be singularized</param>
/// <param name="inputIsKnownToBePlural">Normally you call Singularize on plural words; but if you're unsure call it with false</param>
/// <returns></returns>
public static string Singularize(this string word, bool inputIsKnownToBePlural = true)
{
    return Vocabularies.Default.Singularize(word, inputIsKnownToBePlural);
}
```

And there is no way to change that because the Vocabulary class constructor is internal.
`Humanizer.Inflections.Vocabulary`

Thats for my +1

**Comment by Flashfyre** [comment]
I looked into this package just for pluralization as it seems to be the only .NET Core package that supports French, but without the ability to specify culture/locale, I can't actually use it. It's a shame.

**Comment by hazzik** [comment]
Passing CultureInfo to Transform was done in #1063. 

`Singularize`/`Pluralize` is English only and this is unlikely to change.
