### ISSUE TITLE
ToMetric() - hasSpace behaviour with no exponent intended behavior?

### ISSUE THREAD

**Issue by JonasBarka** [Humanizr/Humanizer#772]
ToMetric has an optional parameter *hasSpace* for inserting a space before the exponent.

>1000.ToMetric(hasSpace: true, ) + "m" => "1 km"
>0.001.ToMetric(hasSpace: true, ) + "m" => "1 km"

But the space is not inserted at the end when no prefix is added.

>10.ToMetric(hasSpace:true, ) + "m" => "10m"

Indented behavior? If the main intended usage of ToMetric is to also add a unit, as the name of the method implies, the this seems like a bug. But in isolation not adding it would be more correct.

An option for always adding the space would probably be best, or what do you think?

**Comment by aloisdg** [comment]
I agree to move it to an option.
