### ISSUE TITLE
Pascalize and Camelize do not join words separated by spaces

### ISSUE THREAD

**Issue by wldevries** [Humanizr/Humanizer#774]
My expectation of these methods would be that it would join separate words together.

`"This is a sentence".Pascalize();`

Expected result: `"ThisIsASentence"`
Actual result: `"This is a sentence"`

My workaround for now i to `Underscore` first:
`"This is a sentence".Underscore().Pascalize()`

**Comment by JonasBarka** [comment]
I've checked the source and it seems to be by design.  But I've never encountered camel case or pascal case containing any white space.

Is there any risk of breaking a legitimate use of this behavior if the default is changed to remove all white space?
