### ISSUE TITLE
ToMetric to million not m

### ISSUE THREAD

**Issue by LeahPike** [Humanizr/Humanizer#781]
Would it be possible to use to Metric to have a long format as well?

So instead of 1.3M it would say 1.3 Million?

**Comment by AKTheKnight** [comment]
Just leaving a note to say I'd like to take a crack at this and I'm giving it a go in my fork :)

**Comment by caconstan** [comment]
gonna give this a try!

**Comment by caconstan** [comment]
m is for meters in Metric, not million
