### ISSUE TITLE
Feature Request: Humanize Plural Acronym

### ISSUE THREAD

**Issue by mrlife** [Humanizr/Humanizer#785]
We have instances where we have strings as uppercase or lowercase, and they contain an acronym ending with an 's'. We use Humanizer a lot; would it be possible to add a function to Humanizer that uppercases all the letters expect the last one and lowercases the last one?

e.g. `"urls".HumanizePluralAcronym()` -> URLs

**Comment by AKTheKnight** [comment]
Not sure if this is something you're still after, but this is possible by implementing IStringTransformer yourself. The gist linked below would do what you're trying to achieve:
https://gist.github.com/AKTheKnight/587a93ed19784ae1ae86776d68e288b4

It works by converting all the text to uppercase except if the last letter is an "s".

This can then by used via `"urls".Transform(new ToPluralCase());` to give URLs

Let me know if you have any issues

**Comment by AKTheKnight** [comment]
Not sure what peoples thoughts are on adding this into Humanizer itself?

It's a pretty easy implementation so could just be documented in a wiki as an option instead of being adopted in.

**Comment by mrlife** [comment]
Thanks, this is completely acceptable as a solution.
