### ISSUE TITLE
Humanizer Core still using previous previous humanizer installation

### ISSUE THREAD

**Issue by RobinLaevaert** [Humanizr/Humanizer#786]
Installed Humanizer then deleted it since I only need English, after installing humanizer Core in Xamarin forms it still uses the localizes language, tried uninstalling the app and redeploying but no succes. 
I have tried to deploy to an emulator and there it displays the correct language. 
Is there a way to reset the Humanizer package on a device ?

**Comment by onovotny** [comment]
Not really following? If you uninstall all the nuget packages, it will be gone and you can install whatever version you want.

**Comment by EmmanuelJego** [comment]
I had the same problem. I had to clean the app data and cache on my device in order to make it works.

**Comment by SimonCropp** [comment]
This sounds like a nuget isseu
