### ISSUE TITLE
Word doenst pluralize

### ISSUE THREAD

**Issue by kevinmarchand** [Humanizr/Humanizer#788]
I Can't use pluralize with this word "Equipment" even by addind a default....

Vocabularies.Default.AddPlural("Equipment", "Equipments");
Vocabularies.Default.AddIrregular("Equipment", "Equipments");

var s = "Equipment";
Console.WriteLine(s);
Console.WriteLine(s.Pluralize());
Console.ReadKey();

**Comment by rothschild86** [comment]
Equipment is always singular/unmeasurable. Equipments is not a word ;)

**Comment by hazzik** [comment]
Closing as per @rothschild86
