### ISSUE TITLE
Singularize Caches gives cach

### ISSUE THREAD

**Issue by solankisamir** [Humanizr/Humanizer#789]
"Caches".Singularize().Dump() => "Cach"
I would expect
"Caches".Singularize().Dump() => "Cache"

how to achieve this?

**Comment by AKTheKnight** [comment]
Added a new test in my repo and confirmed reproducable: https://github.com/AKTheKnight/Humanizer/commit/1aaf185cf7e9b1b82bcda76bb9cd25f1a5613811

Interestingly, pluralizing cache does give the right value, so the issue is only with singularize.
"Cache".Pluralize() => "Caches"

**Comment by AKTheKnight** [comment]
This regex: "(x|ch|ss|sh)es$" is the one we're calling to Singularize "caches"

https://github.com/Humanizr/Humanizer/blob/d5b3cf3fd081733dd2ccb3e13a35af8ffe987415/src/Humanizer/Inflections/Vocabularies.cs#L61

Not sure what the best method for solving this is, should we add a default or look and reworking some regex (Not sure how we could fix it without breaking other tests).

@solankisamir To fix this issue for you, just call the below code at the start of your program, and that will add the "cache", "caches" link into the Vocabulary for the running program:
```
Vocabularies.Default.AddIrregular("cache", "caches", false);
