### ISSUE TITLE
ByteSize symbols should be translated

### ISSUE THREAD

**Issue by jeremyVignelles** [Humanizr/Humanizer#810]
Hi,
I'm French, and I'm using Humanizer to display TimeSpans and Byte size in a human readable-format.

However, in France, the term "byte" doesn't exist, except for programmers, and the word "octet" is used instead.

A few examples of english units VS french ones :
- `MB` => `Mo`
- `kB` => `ko`
- `kb` => `kb`

When non-technical folks read "MB", they will read it as "Méga Bits", which is a _bit_ different.

For reference, here is how Windows shows the file sizes:
![image](https://user-images.githubusercontent.com/3399355/56198421-36c92680-603b-11e9-9670-aabb5f20a9fa.png)

**Comment by louis-z** [comment]
I've begun implementing this... I too feel that data unit symbols should be displayed according to culture.

**Comment by louis-z** [comment]
Just submitted an initial version. It could be simplified a bit, but I strove to limit breaking API changes... If that's not a concern, I could give it another shot.
