### ISSUE TITLE
`0.Bytes().Humanize("#.## B")` returns " B"

### ISSUE THREAD

**Issue by icnocop** [Humanizr/Humanizer#811]
Hi.

I noticed that `0.Bytes().Humanize("#.## B")` returns `" B"` instead of `"0 B"`.

As a work-around, I have to check if the value is `0` then use `myvar.Bytes().Humanize("0 B")` for example.

Related to https://github.com/Humanizr/Humanizer/issues/450

Humanizer 2.6.2 in .NET Framework 4.5.2.

Thank you.

**Comment by AKTheKnight** [comment]
Yeah this is definitely related to #450. The final step for 
```0.Bytes().Humanize("##.# B")``` 
is (With values replaced with variable names)
``` return 0.ToString("#.## B", NumberFormatInfo.CurrentInfo)```.

This is the same as https://github.com/Humanizr/Humanizer/issues/450#issuecomment-131316811
> The `ToString()` method will ignore the digit if it is zero. Providing the string format as `0.Bytes().ToString("0.##")` will return `0 b`.

We do currently have a bit where we set the format to 0.## if there is none provided, but that doesn't account for situations like this.

I'll take a look at what we can do, perhaps we just replace #.## with 0.## if we find it. Gonna try this and see if it breaks any tests :)
