### ISSUE TITLE
Humanizer with .Net framework 4.6.2

### ISSUE THREAD

**Issue by LaTiNoDiaz** [Humanizr/Humanizer#813]
Hi, 

When I add Humanizer.Core to my C# desktop application targeting .net 4.6.2 a enormous number of System.xxx dlls appear in my output folder.
When targeting 4.7.2 this doesn't happen.
Does this mean Humanizer v2.6.2 depends on .Net Framework 4.7.2 and I need to deploy all those System.xxx dlls with the application when targeting 4.6.2?

Thanks

**Comment by ygel** [comment]
Humanizer is a Net Standard 2.0 library:
![image](https://user-images.githubusercontent.com/51912343/69740305-ccaf4e80-10fe-11ea-9af0-0a898ee716a7.png)

NetFx 4.7.2 is first framework with full Net Standard 2.0 support, NetFx 4.6.2 needs these .dlls and binding redirects to work with Humanizer: https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET#the-first-version-that-fully-net-standard-20-compliant-is-472
