### ISSUE TITLE
ByteSize with no overload for subtraction

### ISSUE THREAD

**Issue by SzybkiDanny** [Humanizr/Humanizer#819]
The documentation for ByteSize says:

> You can also add/subtract the values using +/- operators and Add/Subtract methods

And then follows with an example:

`var total = (10).Gigabytes() + (512).Megabytes() - (2.5).Gigabytes();`

Unfortunately, it doesn't work and after looking at the source, I can confirm there is an appropriate overload missing for `-` operator.

There is, however, a unary operator defined for subtraction so one can achieve the same result with:

`var total = (10).Gigabytes() + (512).Megabytes() + -(2.5).Gigabytes();`

Could you, please, update the docs or add the overload.

**Comment by SzybkiDanny** [comment]
Thank you for the reaction

**Comment by Ashera138** [comment]
It looks like this issue can be closed. 👍
