### ISSUE TITLE
DateHumanize_MultipleHoursAgo in polish

### ISSUE THREAD

**Issue by jemunk** [Humanizr/Humanizer#830]
In version 2.6.2

For one user we are getting a System.ArgumentException: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found Parameter name: resourceKey
The user is having his UI set to Polish

**Comment by AKTheKnight** [comment]
Hi @jemunk,

It seems there is a value for MultipleHoursAgo in the polish translations:
https://github.com/Humanizr/Humanizer/blob/23c4c2a526deb0f101b39fe060fca66f5e66c823/src/Humanizer/Properties/Resources.pl.resx#L135-L137

Any chance you could show the code you are using?

**Comment by peppy** [comment]
Also a duplicate of #690.

**Comment by Filipowicz251** [comment]
I have stil the same bug after one year. I've included Humanizer.Core and Humanizer.Core.Pl as a nuget for my Android version - but it is throwing this error all the time...

**Comment by praksis-jw** [comment]
We are experiencing the same issue in xamarin forms. Only Android - IOS works fine. Is there any possible way to fix this?

**Comment by KSemenenko** [comment]
any updates?

**Comment by KSemenenko** [comment]
I have the same issue for some languages on Andoird, iOS works fine

**Comment by daflotsch** [comment]
We have the same issue on WPF (as dotNet 6) with Polish language: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found (Parameter 'resourceKey')
Any chance this can be fixed? Thank you

**Comment by hazzik** [comment]
Duplicate of #690
