### ISSUE TITLE
Mono Linker doesn't link resources for Blazor

### ISSUE THREAD

**Issue by enisn** [Humanizr/Humanizer#852]
Localization doesn't work on Blazor. 

Following dlls are linked:
`Humanizer.dll`
`Humanizer.resources.dll`

But none of `{culture}/Humanizer.resources.dll` are linked.

**Comment by onovotny** [comment]
I would file an issue on https://github.com/mono/linker. There's not much we can do on our end.

**Comment by enisn** [comment]
I've just posted an issue related with that:

[Mono Linker - #739](/mono/linker/issues/739)

**Comment by enisn** [comment]
Visit related original issue to see solution. It's closed there: 

> I've just posted an issue related with that:
> 
> [Mono Linker - #739](/mono/linker/issues/739)
