### ISSUE TITLE
Moving all language packages to a sub-folder in build output

### ISSUE THREAD

**Issue by sommmen** [Humanizr/Humanizer#858]
Hello,

I have setup my project in a way that all reference dlls etc are in a /lib folder, so e.g. Bin/Debug/Lib.
Humanizer pushes a lot of culture/lang folders to the output folder. 
Could I have them moved to the same sub directory?

Right now I use a post build script to move the files to the subdir. I then have probing setup to the /lib sub folder so the executable finds the dlls.

**Comment by onovotny** [comment]
Subfolders per culture in the output directory are how the .NET Resource Manager locates culture specific resource assemblies.

**Comment by sommmen** [comment]
> 
> 
> Subfolders per culture in the output directory are how the .NET Resource Manager locates culture specific resource assemblies.

So you see no chance of being able to move those to a subdirectory? Or embed them or something?

**Comment by onovotny** [comment]
That's not how .NET works:
https://docs.microsoft.com/en-us/dotnet/framework/resources/packaging-and-deploying-resources-in-desktop-apps#ultimate-fallback-to-satellite-assembly

What are you trying to do, what's the concern?

**Comment by sommmen** [comment]
> 
> 
> That's not how .NET works:
> https://docs.microsoft.com/en-us/dotnet/framework/resources/packaging-and-deploying-resources-in-desktop-apps#ultimate-fallback-to-satellite-assembly
> 
> What are you trying to do, what's the concern?

I had never worked with languages files before, but thanks for the info.
The only (minor) concern I have is keeping a clean output folder. I'd rather had the language folders in a subdirectory.

When 'deploying' our software we usually copy the new assemblies over the old ones so things like setting files etc. are not overwritten. looking for the settings folder inbetween all those language files is difficult. I may at some point look at the whole strategy anyways since some things have changed.

I think I know enough for now, and if you have nothing to add I can close this issue. Thanks for your support - I hope to start using the library pretty soon.
