### ISSUE TITLE
Error on MVC Razor views after installing Humanizer

### ISSUE THREAD

**Issue by ciaran036** [Humanizr/Humanizer#859]
I have an ASP.NET MVC v4.6.1 web project. When I installed Humanizer, the Razor intellisense now shows an error message similar to this to this on all HtmlHelper functions: 

> The type 'Expression<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Core, Version 4.0.0.0"...

It only seems to affect the Intellisense on views. The views still work fine, but there are errors throughout the views. They don't go away with restarting Visual Studio, rebuilding etc. 

I tried updating the project to v4.7.2 and reinstalling Humanizer but the problem persists. [StackOverflow ](https://stackoverflow.com/questions/31086850/the-type-expression-is-defined-in-an-assembly-that-is-not-referenced?rq=1)offers a number of suggested solutions for this error but none seem to resolve the problem.

The problem appears to disappear when Humanizer is uninstalled. Any ideas why this is happening?

I'm not clear on whether this is happening with some sort of fault with Humanizer or not.

**Comment by SimonCropp** [comment]
This should now be fixed
