### ISSUE TITLE
Is there a way to "dehumanize" human readable date like "Tomorrow" to a dateTime?

### ISSUE THREAD

**Issue by saroup** [Humanizr/Humanizer#861]
It would very useful to have something that takes in things like 
"Tomorrow"
"In 2 weeks"
"Next Month"
"Yesterday" 
and turns it into a DateTime Object

**Comment by erikvojtko** [comment]
Hi, can I work on this Issue?

**Comment by hazzik** [comment]
Duplicate of #691

**Comment by hazzik** [comment]
In short. There is no built in way to do this. Here is a future request #691 and older closed issue #112.
