### ISSUE TITLE
BolgarianNumberToWordsConverter should be renamed to BulgarianNumberToWordsConverter

### ISSUE THREAD

**Issue by NikolayIT** [Humanizr/Humanizer#880]
`BolgarianNumberToWordsConverter` should be renamed to `BulgarianNumberToWordsConverter`. The correct naming is Bulgarian.

https://en.wikipedia.org/wiki/Bulgarian_language

**Comment by AKTheKnight** [comment]
This can be closed now :)

**Comment by hazzik** [comment]
Fixed by #882
