### ISSUE TITLE
Singularize/Pluralize 

### ISSUE THREAD

**Issue by haraldchr** [Humanizr/Humanizer#891]
Does this only work for English ?
Given this code

```
using System;
using System.Globalization;
using System.Threading;
using Humanizer;

namespace SingularAndPlural
{
    class Program
    {
        static void Main(string[] args)
        {
            string[] cultures = { "en-US", "no", "no-NB", "sv", "da", "fi-FI" };
            string[,] words =
            {
                {"School", "Sack", "Car", "Chicken", "Person", "Gastation","Man"},
                {"Skole", "Sekk", "Bil", "Kylling", "Person", "Bensinstasjon","Mann"},
                {"Skole", "Sekk", "Bil", "Kylling", "Person", "Bensinstasjon","Mann"},
                {"Skola", "säck", "Bil", "kyckling", "Person", "bensinstation","Man"},
                {"Skole", "Sæk", "Bil", "Kylling", "Person", "Tankstation", "Mand" },
                {"Koulu", "säkki", "auto", "kana", "henkilö", "huoltoasema", "ihminen"}
            };

            Console.WriteLine("\nBegin singular and plural words demo");
            Console.WriteLine("Example of Humanizer\n");

            Console.WriteLine("Current Culture "+ CultureInfo.CurrentCulture.Name);
            Console.WriteLine("Current UICulture " + CultureInfo.CurrentUICulture.Name);

            //foreach (string culture in cultures)
            for(int i = 0; i < cultures.Length;i++)
            {
                string culture = cultures[i];
                Console.WriteLine();
                Console.WriteLine("Setting CurrentThread Culture to");
                CultureInfo newCulture = CultureInfo.CreateSpecificCulture(culture);
                Thread.CurrentThread.CurrentUICulture = newCulture;
                CultureInfo ci = Thread.CurrentThread.CurrentCulture;
                CultureInfo ciUi = Thread.CurrentThread.CurrentUICulture;

                Console.WriteLine("CurrentThread Culture " + ci.Name);
                Console.WriteLine("CurrentThread UICulture " + ciUi.Name);
                Console.WriteLine();

                Console.WriteLine("Entall\t\tFlertall");
                //foreach (string word in words)
                for(int y = 0; y<7;y++)
                {
                    Console.WriteLine(words[i,y] + "\t\t" + words[i,y].Pluralize());
                }

                Console.WriteLine();
                Console.WriteLine(DateTime.Now.AddHours(-30).Humanize());
                Console.WriteLine(DateTime.UtcNow.AddHours(-2).Humanize());
                Console.WriteLine(DateTime.Now.AddHours(-30).Humanize(culture: ciUi));
                Console.WriteLine(3501.ToWords());
                Console.WriteLine(2019.ToRoman());
            }

            Console.WriteLine("\nEnd demo\n");
            Console.ReadLine();
        } // Main
    } // Program
}
```

Produces this output:

> Begin singular and plural words demo
> Example of Humanizer
> 
> Current Culture nb-NO
> Current UICulture nb-NO
> 
> Setting CurrentThread Culture to
> CurrentThread Culture nb-NO
> CurrentThread UICulture en-US
> 
> Entall          Flertall
> School          Schools
> Sack            Sacks
> Car             Cars
> Chicken         Chickens
> Person          People
> Gastation               Gastations
> Man             Men
> 
> yesterday
> 2 hours ago
> yesterday
> three thousand five hundred and one
> MMXIX
> 
> Setting CurrentThread Culture to
> CurrentThread Culture nb-NO
> CurrentThread UICulture nb-NO
> 
> Entall          Flertall
> Skole           Skoles
> Sekk            Sekks
> Bil             Bils
> Kylling         Kyllings
> Person          People
> Bensinstasjon           Bensinstasjons
> Mann            Manns
> 
> i går
> 2 timer siden
> i går
> tretusenfemhundreogen
> MMXIX
> 
> Setting CurrentThread Culture to
> CurrentThread Culture nb-NO
> CurrentThread UICulture no-NB
> 
> Entall          Flertall
> Skole           Skoles
> Sekk            Sekks
> Bil             Bils
> Kylling         Kyllings
> Person          People
> Bensinstasjon           Bensinstasjons
> Mann            Manns
> 
> yesterday
> 2 hours ago
> yesterday
> three thousand five hundred and one
> MMXIX
> 
> Setting CurrentThread Culture to
> CurrentThread Culture nb-NO
> CurrentThread UICulture sv-SE
> 
> Entall          Flertall
> Skola           Skolas
> säck            säcks
> Bil             Bils
> kyckling                kycklings
> Person          People
> bensinstation           bensinstations
> Man             Men
> 
> igår
> för 2 timmar sedan
> igår
> tre tusen femhundraett
> MMXIX
> 
> Setting CurrentThread Culture to
> CurrentThread Culture nb-NO
> CurrentThread UICulture da-DK
> 
> Entall          Flertall
> Skole           Skoles
> Sæk             Sæks
> Bil             Bils
> Kylling         Kyllings
> Person          People
> Tankstation             Tankstations
> Mand            Mands
> 
> i går
> 2 timer siden
> i går
> three thousand five hundred and one
> MMXIX
> 
> Setting CurrentThread Culture to
> CurrentThread Culture nb-NO
> CurrentThread UICulture fi-FI
> 
> Entall          Flertall
> Koulu           Koulus
> säkki           säkkis
> auto            autos
> kana            kanas
> henkilö         henkilös
> huoltoasema             huoltoasemas
> ihminen         ihminens
> 
> eilen
> 2 tuntia sitten
> eilen
> kolmetuhatta viisisataayksi
> MMXIX
> 
> End demo

---
Am I to conclude that Pluralize() only supports English language or am I missing something here?

regards Harald

**Comment by LeoJHarris** [comment]
@haraldchr I'd be interested to know as well. While we havnt used the Pluralize method, we do have cases where it would be useful.

**Comment by hazzik** [comment]
Yes, currently these are English-only methods. See #197

**Comment by haraldchr** [comment]
@LeoJHarris !
I ended up building a separate DLL for each language, each with a their own set of rules. At application startup I load the appropriate DLL according to Windows Culture settings.
