### ISSUE TITLE
Humanizer.resources.dll is built in debug mode (WACK report)

### ISSUE THREAD

**Issue by maxkatz6** [Humanizr/Humanizer#920]
Hi!
When I run Windows App Certification Kit to validate my UWP appxbundle package, it fails with next message:
![image](https://user-images.githubusercontent.com/3163374/78737884-955b7480-791e-11ea-86b6-e59257d34b50.png)

In fact, it doesn't impact store submission, so I can easily ignore that issue.
However I want to ask, is it expected behavior?

Used package: Humanizer v2.7.9 (with all languages).
TargetFrameworks: netstandard1.4, uap10.0.10240 (with MSBuild.Sdk.Extras)

**Comment by clairernovotny** [comment]
All of the binaries are being built in the same way. I suspect WACK is incorrectly handling satellite resource assemblies.

**Comment by maxkatz6** [comment]
@clairernovotny 
Thanks for answer!
I have created issue with Visual Studio:
https://developercommunity.visualstudio.com/content/problem/985020/humanizerresourcesdll-is-built-in-debug-mode-wack.html

**Comment by maxkatz6** [comment]
I will close issue, because it seems like a bug in WACK.
