### ISSUE TITLE
Humanizer output clutter

### ISSUE THREAD

**Issue by reader-man** [Humanizr/Humanizer#929]
Hi,
Thanks a lot on the very excellent work you have done.
It would be great if you can help in making a version that will list all the language resources to go to one folder in the bin directory, e.g.:
bin\debug\humanizer
that will minimize the clutter of the too many folders it outputs.
also, if there is a command/setting to combine all the small resources under one file, as they are very small, but too much in numbers of files/folders.

Regards.

**Comment by cimpok** [comment]
I came here to make a comment on exactly the same issue.
It is very annoying each time to see/scroll thru/handle/delete those plethora of language resources cluttering the very main directory of any project whose developers chose Humanizer as a dependency. 
Could you please consider to be a little less arrogant with the directory structure and not occupy our top level folders with this?  Thank you.

**Comment by clairernovotny** [comment]
This is the way .NET resource localization works. There is no other supported directory structure.

**Comment by cimpok** [comment]
Thank you Claire.  I will then raise this issue to the .NET guys if I find them. Am I the few who is annoyed with it?
Let's hope you will never localize this more than to 1% of the 7117 languages spoken in the world, it would then really render the whole thing unmanageable.

**Comment by reader-man** [comment]
@clairernovotny thanks, and sorry for the comment, i thought that there might be a runtime way to solve this.
@cimpok thanks.
