### ISSUE TITLE
DutchNumberToWordsConverter.ToWords support for big numbers (Int64.MaxValue)

### ISSUE THREAD

**Issue by Terra-jin** [Humanizr/Humanizer#930]
This issue concerns adding support for converting big numbers (longs) to words in Dutch. Since the existing ToOrdinalWords extension does not support longs, only the Convert method, called by the ToWords extension, is updated.

I'd like to create a PR, but according to the [contribution guidelines](https://github.com/Humanizr/Humanizer/blob/master/CONTRIBUTING.md) I should base my feature branch on `dev`, which doesn't seem to exist. Can I use `master`?

**Comment by clairernovotny** [comment]
Please, yes. I updated the guidelines to reflect that.
