### ISSUE TITLE
Compiler Error Message: CS0246

### ISSUE THREAD

**Issue by HGCollier** [Humanizr/Humanizer#932]
I'm developing a website (VS 2020, Target Framework: 4.7.2) and want to use the Humanizer package on a search. However as soon as I add the `using Humanizer` statement it gives me this error:

```
Compiler Error Message: CS0246: The type or namespace name 'Humanizer' could not be found (are you missing a using directive or an assembly reference?)```
```
```
Line 3:  @using Site.Core.Models
Line 4:  @using Examine.Search
Line 5:  @using Humanizer
Line 6:  @{
Line 7:      Layout = "Page.cshtml";
```

**Comment by SimonCropp** [comment]
Closing for now.

If you have a stand alone repro, please share and we can revisit
