### ISSUE TITLE
Make string formatting `IFormattable` for simplified string interpolation

### ISSUE THREAD

**Issue by philcarbone** [Humanizr/Humanizer#933]
Currently I am using the library for things like this:
``` csharp
var message = $"Your file is this big: {fileSize.Bytes().ToString("#.##")}";
```
If I tried to shorten it to this:
``` csharp
var message = $"Your file is this big: {fileSize.Bytes():#.##}";
``` 

It won't work because `ByteSize` isn't `IFormattable`.

Here is the `IFormattable` interface (for reference):
``` csharp
  public interface IFormattable
  {
    string ToString(string format, IFormatProvider formatProvider);
  }
```

**Comment by philcarbone** [comment]
See PR: https://github.com/Humanizr/Humanizer/pull/934

**Comment by vip32** [comment]
is this a regression issue? as the shortened variant was working fine until the latest 2.8.26 version

```
$".... size={message.Length.Bytes():#.##})"
```
causes this exception:
Value cannot be null. (Parameter 'provider'

**Comment by clairernovotny** [comment]
@vip32 Maybe, sorry about that. Can you please add a PR with a failing unit test?

**Comment by vip32** [comment]
Hi Claire, here you go
https://github.com/Humanizr/Humanizer/pull/944
