### ISSUE TITLE
General Bugs Found

### ISSUE THREAD

**Issue by Josh-Fry** [Humanizr/Humanizer#975]
Using the Pluralizer - Humanizer.Core v2.8.26 (Latest Release)

Input: Ex
Output: Ices

Input: Octopi
Output: Octopis

Input: Ox
Input: Oxen
Output: Oxens

Input: **blank**
Output: s

Input: Kale
Output: Kales

**Comment by AlexCinetic** [comment]
Hi there, I have a couple comments on the bugs you found:

> Input: Octopi
Output: Octopis

I'm not sure the Pluralize method is suposed to ignore a word that is already plural.

> Input: Kale
Output: Kales

Kale ca be countable and uncoutable, but it could be added in the uncountable depending on the wish of the author.
